#+TITLE: 中轴
#+CREATED:       [2020-12-10 Thu 14:41]
#+LAST_MODIFIED: [2020-12-10 Thu 14:56]

作者： 李文龙
出处: http://bbs.casdu.cn/forum.php?mod=viewthread&tid=11899

从大类上分为方孔中轴、花键中轴、穿钉式中轴、一体式中轴。分别对应专用规
格的牙盘。

安装方式上分为旋入式和压入式。

其中旋入中轴根据螺纹外径分为英规中轴和意规中轴。

* 方孔中轴

** 简介
方孔中轴最为常见，因为两头都是正方形，所以容易识别。它是在传统的销钉式
中轴的基础上通过改进而来的。销钉式中轴是通过单颗销钉进行锁紧，因接触面
较小而容易发生松动进而损坏。只能见于相当老式的民用车中。方孔中轴的性能
提升就在于将1个接触面增加到4个，受力更加均匀，强度更高，力量传导的更好，
因而主导市场相当长的一段时间。各个厂家都有方孔中轴的型号 方孔中轴在自
行车上存在几十年，是曾经使用规模最大的中轴规格之一，目前正在逐渐被其他
规格替代，但目前其应用规模也很大，部分中低端车仍然在使用这个规格的中轴。
** 使用车型
在山地车和公路车上都有应用，根据五通规格又分为英规和意规两种，意规只有
公路车型，都是正螺纹，螺纹外径为 36 mm，牙距为1.37*24 TPI。英规（BSA)
中轴为一正一反螺纹。螺纹外径为 34.798 mm。牙距为 1.37*24 TPI，五通宽度
为 68mm 或 73mm 以及更宽的 DH 车型。通常来说，绝大部分车架都在使用英规
中轴，我们一般的车架也都能安装。配套使用的是方孔牙盘。

上图就是常用的方孔中轴和方孔牙盘，常用品牌主要有景晔、禧玛诺和一系列台
湾品牌，以及部分欧美高端钛合金中轴，主要在复古高端车上使用。方孔中轴将
原来老式的一个受力点变为四个，大大提高了中轴的耐用性，但其密封性依然不
佳，而且拆装比较麻烦,需要专业的工具和复杂的步骤。

** 安装步骤
- STEP1
准备工具：拉马、扳手、中轴拆卸器、大号内六角

- STEP2
拆牙盘锁定螺丝，用大号内六角扳手将牙盘和另一侧的螺丝拧下来

- STEP3
拆牙盘和曲柄，将牙盘拆卸器一头旋入牙盘，然后用扳手拧紧。

- STEP4
将后面的部分用扳手拧紧直到牙盘被顶出（左侧曲柄类似），安装时套上牙盘和
曲柄拧上先前拧下的锁定螺丝就可以了。

- STEP5
接下来拆中轴，将中轴拆卸器套在中轴上，用扳手将其拧下，需要注意的是：手要扶住中轴拆卸器（防止发力时脱出），再发力拧，另一边相同。

- STEP6
用润滑脂保养五通

- STEP7
装好中轴，需注意螺纹正反

- STEP8
然后把牙盘用力上紧即可

* 花键中轴
上个世纪末， SHIMANO 推出了所谓 OCTALINK 的花键（俗称“梅花”）中轴制式，
而其他的厂家（如RACE FACE,TRUVATIV,FSA等）为了抵制 SHIMANO 的技术垄断
就在于一个是8角花键（OCTALINK），另一个是10角花键（ISIS）；一个齿纹较
钝且轴向长度较小（OCTALINK）,另一个齿纹较尖间距较密且轴向长度较大
(ISIS)。花键中轴与方孔中轴相比，接触面更多更细密，与曲柄能更好的结合，
不易松动，轴心直径更大，强度高力量传导好，所以逐渐取代了方孔中轴原有的
地位。花键中轴刚推出没几年，各个厂家有推出了一体中轴的概念，并在其高端
系列中生产。所谓一体式，就是将中轴的轴心与轴承分离，直接与一侧的曲柄结
合在一起，而轴承的位置由五通内移到了两侧。这种制式的优点在于减少了零件
的数目，减轻重量而又提高结构刚性，轴承之间的间距更大，减少了轴承的负担，
提高了强度。其实，这种技术很早就在 BMX（小轮车）当中广泛应用，并不稀奇。
目前在几乎所有的车种都有了一体式中轴技术，但其因为各品牌的车架和牙盘设
计不同，这一大类下的衍生规格也有很多。穿钉式中轴在以前的普通民用车上使
用较多，现在已经几乎找不到，也要用专用的拆装工具，实用性较小，不再详细
介绍。

* 一体中空式中轴
1992年，Shimano开始为大众带来密封轴承中轴，并在1996年推出Octalink，这
是一种更大直径的曲柄轴心，带有全新的曲柄接口。与此同时，Magic
Motorcycle 开发了全新的额外置式中轴，为使用更粗的轴心奠定了基础。随后
是Shimano Hollowtech II 曲柄在2003年亮相，将轴心集成到曲柄中，这基本上
也迎来了当前“中空”曲柄设计的时代。从那时起，曲柄的重量、刚性和可靠性得
到了改善，而它们也变得更易于安装和维修。

Shimano这一中轴系统的特点是：轴心为中空钢制，直径为24mm轴心与培林分离，
培林外置，培林为两颗6805。通过培林外挂，使得培林间隔从原来的68mm（BSA
公路）增加到了86.5mm（山地为91.5mm），此举减少了培林的压力，使得培林寿
命增加。中轴系统的总长变成了90.5mm，这意味着Q-FACTOR会比原来的中轴系统
更宽了。而这对部分骑手来说，会是个问题。一体式中空中轴是目前使用范围最
高的中轴规格，其拥有着安装方便（从安装方式上分为旋入式和压入式。两种中
轴使用的车架无法通用），保养方便，重量轻，故障率小，刚性好，防水性佳，
的特点，但也存在着规格多难以兼容的缺点，许多不同的车架和牙盘都需要不同
的中轴去配合。从安装方式上分为旋入式和压入式。两种中轴使用的车架无法通
用。

Q值：指的是左右曲柄中心点间的宽度，是选用牙盘和中轴时的重要参数轴心直
径：指连接左右曲柄的轴心外径，一般有30mm，24mm，25mm，22mm，50mm，29mm。
这是你选用牙盘的关键数据。在下文会详细解释（又给自己挖坑）目前五通的设
计规律：直径增加，宽度增加，这大大增加了曲柄和车架的侧向刚性。

2001年，Cannondale就联合FSA，在CAAD 6车架上推出了BB30压入式中轴，使用
的就是最经典的BB30结构，宽度为68mm，内径为42mm，使用两个C型环作为限位，
直接将轴承压在车架五通上（碳架则需在五通粘个铝合金轴套）。这样就可以使
用30mm铝合金轴心的BB30牙盘，给牙盘带来更好的抗扭刚性，并且更小的
Q-Factor更易于发力。除Cannondale自家的HollowGram曲柄和FSA外，SRAM也快
速跟进了这个规格。

SRAM 公司针对 BB30 系统的公差要求高和与之相关的制造成本高的问题，在
2009年推出了 Press Fit 30（PF30）系统,它和 BB30 有着同样的培林尺寸和培
林位置，但是增加了一层中间的复合物培林套，这样就可以降低车架公差要求，
有利于更多小规模的车架厂商加入这个阵营。然后canondale推出了一些BB30的
衍生型号如BB30A，PF30A，BB30A-83，PF30A-83。PF30A具有与BB30A相同的不对
称73mm宽度，但具有PF30和46mm的直径。而BB30A-83类型则是具有额外10mm的宽
度，以提供更多的轮胎间隙。以上所有型号Cannondale都在使用。不管是BB30A
还是BB30A-83，Cannondale 都会在车上使用相同的 BB30标志。BB30的培林孔公
差要求是41.96+0.025/-0mm（也就是说培林孔可以稍微大一点，但是不能小了），
PF30的培林孔公差要求是46.00+0/-0.05mm，公差要求差了一倍。顺带一提，
Campy的UT牙盘对BSA五通宽度的公差要求是68mm+0.07/-0.07mm。可想而知，
BB30的公差要求有多高。原本BB30的密封防水性能就比较一般，在恶劣环境骑行
非常容易进水，一个不小心轴承报废之后就需要更换了。但这种轴承和轴套间
“硬碰硬”的连接方式，在多次拆装之后会导致铝合金轴套磨损，从而加大公差，
导致异响的产生。这也是促使PF30出现的重要原因。

那么，为什么 Cannondale 要以车架厂商身份费力的去推出新的BB标准呢？主要
是因为当时的中轴系统以下一些问题：当时广泛使用的花键中轴突显了更大轴心
与BSA五通尺寸之间的矛盾，花键中轴太重，一个差不多要260克，而方孔中轴就
更重了。当时的公路车主流车架已经都是铝架了，而提升铝架刚性的最佳方案，
就是加粗车架各管的管径。但是传统BSA五通狭小的表面积显然已经是影响整个
车架设计的短板了。对于竞争对手这样的“先手”，24mm轴心的“领袖”Shimano自
然不会坐视不管，联合一众车架厂商推出了 BB86 压入式中轴，使用86.5mm宽、
内径41mm的五通来弥补轴心扭转刚性的差距。并且轴承装在塑料轴套中压入车架，
这种“软碰硬”的安装方式可以降低对五通精度的要求，车架厂商也可以使用全碳
纤维五通来降低车架重量，同时降低成本。尼龙衬套的加入也在一定程度上降低
了操作不当损坏五通和异响的几率。通过转换中轴，BB86也可以使用BB386规格
的轴心牙盘。所以BB86是近年最常见的压入式五通规格。

多年来，很多车友一直都误以为BB30采用30mm轴心（配合使用6806培林），是基
于ShimanoHollowtech II/GXP系统的24mm轴心（配合使用6805培林）进一步改进
升级而来的。这么想也很正常，毕竟6806刚好是比6805大了1个尺寸的标准工业
轴承。而事实上，我们从BB30诞生年份（2001年）就可以知道，BB30从来都不是
基于Hollowtech II（2003年），反而是更早于它。BB30和Hollowtech II之间没
有传承关系，而是路线选择之争。为了解决问题，Cannondale这样的车架厂商选
择了把BSA五通变粗，而Shimano为首的套件厂商为了向下兼容，而选择了沿用
BSA，但是通过将培林外挂，把五通加长。BB90是Trek车架专用的中轴，BB90是
Trek联合Shimano在2007年的Madone上推出的压入式规格。做法十分激进，直接
将轴承压在车架五通的碳纤维台阶上，并且中轴端盖与五通形成一个平面，这使
得五通宽度加宽到90.5mm、内径37mm，从而得名BB90。但其兼容性很差，不能安
装粗轴心牙盘。而且其配合间隙很大，有些车型中轴可以直接“放进去”，后来
Trek推出了V2版，增大了0.1mm外径，但依然是亡羊补牢。

BB386是PF30和BB86五通的结合体，具有BB86的宽度。这个规格其实最早是
Wilier公司最早想出来的（2010年至2011年期间，基本也就是BBright的开发时
期）。在车架设计过程中，Wilier首先找到他们的主要合作方Campagnolo，问他
们能不能针对BB386规格开发一款转换套，以便Campagnolo的UT牙盘可以用在新
的车架上，但Campagnolo表示无法按时完成开发工作（估计精力都在PT牙盘的开
发上了）。无奈Wilier只能去找FSA，看看FSA能不能帮他们开发一款适用的牙盘；
而巧的是，BH公司正好也基于相同的理由找上了FSA（BH计划中的五通规格是
80mm宽，和BB386还不完全一致）。FSA综合考虑下来，觉得BB386的方案通用性
更强，因而同意对此进行开发，并说服了BH公司放弃他们的方案（Thank God,
否则又得多一种），一起使用Wilier的这个方案。这个规格也几乎只有willer和
BH使用过，但其最大的优点实际上是牙盘的兼容性，BB386五通兼容市面绝大多
数现有的牙盘，除了是那些专门给BB30/PF30或BBright系统（轴心太短）设计的。
而反过来，BB386牙盘也可以应用于绝对大多数车架，除了Trek的
BB90。特别是对于很多使用旧款BSA五通设计的车架来说，他
们只需要一个转接套就也可以用上最新30mm轴心的牙盘了。

GXP规格是SRAM的规格与Hollowtech II不兼容。区别在于非驱动侧的轴心直径是
ISIS系统沿用过来的10角花键。同样有与之相匹配的中轴，GXP与Shimano采用相
同24mm轴心，但两者在轴心末端有着较大的差异——Shimano 的轴心保持不变，而
GXP 的轴心缩减至 22mm，为非驱动侧的轴承提供一个台阶。BBright又名BB79，
是Cervelo和车架专用中轴 BB Right是在BB30基础上做优化。如果认真看过BB30
牙盘的腿就知道，这牙盘的曲柄都外撇非常厉害，也算是小Q-factor的代价。BB
Right就想两条腿都少撇一点，驱动侧的曲柄起点在大盘之外（BB30的驱动侧曲
柄起始点在大盘内测，与小盘平齐）。然后五通整体往左边伸出来11mm，即五通
总宽度为68+11=79mm。目前Cevelo部分车型采用此结构。BBright五通最大的问
题则在于：一大票短轴心的BB30和PF30规格的牙盘就没办法用了，虽然近年的部
分BB30牙盘也适当加长了轴心以适用于BBright。关于BBright的异响案例，网络
上看到的相对比较少,想来是因为Cervelo的车架加工精度比较高的缘故。但也听
到有人抱怨，原厂培林套与车架外缘之间打滑而导致异响的案例。还有BB386EVO、
BB95、BB92等压入式中轴规格都是衍生规格，但目前还没有任何一个规格有统一
当前市场的资本和能力。

Campagnolo在Hollowtech II推后的四年后（2007年），才姗姗来迟的将他们牙
盘的中轴从方孔升级到了外挂式中轴，并取名ULTRA TORQUE（“UT”）。其特点在
于：轴心采用全空心设计，材质为钛合金，轴心直径25mm。整个轴心一分为二，
分别连接在两侧曲柄，两个轴心后通过端齿盘（Hirth joint）在五通中心连接，
然后再用一颗10mm内六角螺丝锁定（要求扭力:50牛米）。HJ咬合的好处非常多，
比如可以保证高转速大负载下的传输效率，结构简单（两个齿面，一个固定部
件），力传输无延迟，自对齐(Self-centering)。而中轴的两颗培林也采用了与
shimano不同的固定方案，它们在出厂时被直接固定在了齿柄和轴心连接处，而
不是外挂的盖体内，旋入五通左右的两个外挂部件更像是一个衬托住培林的“空
中碗”。这么做的好处在于：

1. 大大简化和降低了技师和用户的工作量，因为培 林出厂时就已经安装到位了；
2. 轴心比shimano大了1mm，理论刚性更高了；
3. 只需要通过更换“外挂碗”，就可以让UT牙盘适用于各种不同规格的中轴（这
   一优点在BB30以后的年代，更是显得弥足珍贵）。

UT牙盘的缺点则在于：牙盘制造成本远高于竞争对手；因为HJ咬合这一非常规的
设计，为确保咬合充分，故而对五通的宽度的精度要求非常高，例如：如果你的
BSA五通宽度小于67.3mm，那么在装上UT牙盘，非常容易出现异响。受限于UT牙
盘的高成本，Campy在2011年又推出了相对低成本的外挂中轴系统，即POWER
TORQUE（“PT”）。不再采用两段式的轴心设计，而是和Hollowtech II同样将其
固定在驱动侧牙盘上了。驱动侧的培林设计依然和UT一样，出厂已安装在轴心末
端，非驱动侧的设计同样和Hollowtech II一样，直接压入外挂壳中。原来的PT
结构在拆装时非常麻烦，而且容易大力出奇迹，甚至还会需要专用工具和拉玛，
新的改进版PT PLUS结构只需要一根14mm内六角扳手就可以完成拆装。而在2012
年，Campy又一步推出了名为Over-Torque（“OT”）的牙盘（一共两款comp
ultra, comp 1），OT牙盘系为了赶上30mm轴心的热潮，而专门研发的BB30版的
牙盘组（通过换碗，也可以用于其它BB30的五通）。严格意义上说，
OVER-TORQUE只能算是一个牙盘方案，而非中轴方案。螺纹中轴主要有英规
（BSA），意规（ITA），最新的T47规格和M48规格

* 螺纹中轴的各种规格
英规上文我们提到过，其特点是左右旋入方向不同，左反右正，1.37*24TPI螺纹，
轴长68mm。我们生活中能见到的几乎所有螺纹五通都是BSA规格。很多规格例如
GXP等都会有英规螺纹的中轴可以选用ITA在很多古典钢架车上使用较多，近几年
市场份额逐渐被其他规格替代，但也有很多知名品牌使用ITA中轴。pinarello就
是使用的ita螺纹中轴配合Shimano规格牙盘，在大环赛一众压入轴中独领风骚。
目前来说，T47绝对是最具有一统天下资格的中轴规格。

T47的别名又叫Thread Fit 30i，使用46mm内径，并和PF30使用相同的轴承规格，
但通过与ThreadFit82.5一样的螺纹固定方式。本质上T47与PF30和BB386EVO相同，
因此可以兼容几乎所有牙盘规格。据说如果五通是金属轴套的PF30或BB386的话，
还可以自行攻牙改成T47……（请勿随意尝试）。T47解决压入式中轴的公差问题，
同时兼具30mm轴心系统的性能优势。金属车架改为使用T47非常方便，几乎没增
加多少重量，所以受到了一众手工定制品牌的青睐。但碳纤维车架使用T47的话
需要在五通粘铝合金轴套，这将付出100克左右的代价，所以是否采用T47就要看
厂商的取舍了。

T47的规格，既然上面提到PF30和BB386可以改成T47，那么就意味着T47也存在两
种规格，主要分为内置轴承和外置轴承两种。

一种是五通宽度68mm的版本，可以使用“IB（Internal Bearing）”的内置轴承中
轴安装传统短30mm轴心牙盘，并可通过安装垫圈兼容长轴心牙盘。

“IB”的CK T47中轴如追求性能，不想使用垫圈，那还可以使用“EB（External
Bearing）”外置轴承版本中轴，加大轴承间距来提高性能。

10"EB" CK T47中轴另一种则是五通宽度86.5mm的版本（新一代Domane两边均削
减了0.5MM，宽度为85.5，让使用中轴安装工具更方便），只能使用“IB”内置轴
承中轴以及长轴心牙盘，也可以通过转换套兼容24mm轴心牙盘。简单来说，68mm
宽五通可以按照牙盘轴心规格选择三款中轴，但86.5宽五通就只能使用“IB”版本
中轴。许多中轴品牌都推出了他们的T47中轴，目前它还在推广阶段，如何攻下
中轴这片高地关键要看它后面的表现如何，让我们拭目以待吧。

* 品牌的专有规格
Wilier 以 Campagolo 的 Ultra-Torque 曲柄为基础设计了 BB94（后改名为
BB93）。因为用于固定轴承的轴承杯被预置在 BB90 的车架中，因此并不需要额
外的轴承杯。Willer 提供两种轴承组，一个适用于 Shimano Hollowtech II 曲
柄，另一组兼容 Sram 的 GXP 轴心。压入轴承后可直接安装这些曲柄。这个设
计随后被 BB386 EVO 取代。提到专有规格，就不能不提LOOK的BB65规格。

Look创造了巨大的BB65外壳，以兼容一体式 Zed 曲柄。这个设计与一体式的BMX
曲柄比较类似——需要一个内径为51mm的中轴。而在BB65中，五通的内径为65mm，
宽度为90mm。而曲柄的直径为 50mm。至今为止，Look 的某些车架依旧使用
BB65 中轴（例如 795）。

Specialized为第一代 Venge 2011年）推出的 OSBB 五通为61mm宽，46mm直径。
因此这个规格也被认作是窄版 PF30，几年之后，OSBB 被 OSBB Carbon 和OSBB
Alloy 取代，但这个设计没有什么新颖之处——只是 PF30 和 BB30 换个名称而已。
而对 Specialized 最新的车型来说，这个区别也不存在。根据闪电的说法，他
们的五通加工工艺与其它厂商不同，采用一次打洞的方式，故五通孔的同心共轴
的精度极高。另外，闪电车架一般都会配有Praxis Works的第三方中轴，因此总
体来说，OSBB很少出现异响问题。的OSBB指的是68mm宽，直径42mm的五通，即
BB30。

当COLNAGO推出C60时，这个品牌提出了一个名为ThreadFit82.5的全新五通设计，
ThreadFit82.5 包含一对对锁环，用于将铝制的外壳固定在碳纤车架的五通上。
内径为 41mm，可直接与所有 BB86 中轴兼容。而目前 ThreadFit82.5 依旧是
COLNAGO 一些车架的重要特征之一，其中包括新款 C64.

当Sram刚开始推出其全新的曲柄轴心和中轴系统——DUB（durable unified
bottom bracket）——有两个重要的目标：一是解决超大轴心带来的轴承耐用性问
题；二是确保曲柄如何让兼容市场上的所有的五通规格。该系统的核心是一个
29mm 直径的轴心，看起来微不足道的区别，但 Sram 声称它可以比 30mm 轴心
的曲柄带来更合理的轴承尺寸。因此曲柄能具有同样的轻量优势、更硬的轴心，
而中轴轴承的耐用性与以前的 GXP 相当.当然BB90仍然不能兼容DUB。

* 山地车
MTB因为各种需求，五通宽度一直比公路车宽很多，因此厂家在制造时就在原有
中轴左右上加了5mm以适用于山地车。

BSA，BB30，PF30 和加宽版本的 BB86 是 MTB 最常见的五通规格，五通宽度从
73mm开始。速降以及胖胎车使用更宽的五通设计，但其他数据保持不变。至于轴
心，Shimano 的 24mm 轴心，GXP 和 30mm 轴心占据了市场上的主要份额，然而
SRAM 全新的 DUB 规格在这个简短的列表上增添了一行。但CX，GRAVEL等车型的
出现却并没有选择增加五通宽度，目前只有canondale在重新设计superX是选择
了83mm五通，但却让规格更加复杂，因为更宽的五通往往无法使用公路牙盘，必
须使用专用的MTB牙盘。

一个车架能使用的中轴规格可能也不止一个，同一规格的中轴也会有很多品牌和
等级区分。而且当我们在更换不同规格的牙盘时也不一定需要更换中轴，或许一
个转换套就可以解决你的问题了呀。

* 问题

** 什么时候需要更换中轴？

通处发出异响，或者转动不顺畅，检查脚踏、牙盘，清洁中轴培林后情况未得到
好转。

** 一体式中轴的拆解和保养
工具：

中轴扳手，润滑油，抹布，小刀，内六角扳手。

- STEP1
固定好车后用工具拧下侧边紧迫螺丝，此处的浩盟是用的内六角工具

- STEP2
然后用内六角松开曲柄锁紧螺丝

- STEP3
将链条脱开牙盘，将轴心用手掌或橡皮锤顶出，将轴心擦赶紧，清理轴心和垫圈
的接触处，然后涂上润滑脂。

- STEP4
用中轴扳手将中轴旋下，须注意上面的方向标识，拆装时要记好左右垫圈数量

- STEP5
用稍尖锐物品挑开中轴盖，清理后涂好润滑脂即可

上面所述的拆卸方法适用于生活中能碰到的普通牙盘，有些不同的规格需要用不
同的工具，例如部分禧玛诺中轴需要使用较小的中轴扳手，很多中轴将紧迫螺丝
和锁紧螺丝合二为一，只需要一根内六角即可（campy的中轴就要使用一根14mm
的内六角扳手，很不好找）紧迫螺丝比较容易丢，但规格也有很多种，24mm中轴
就有18mm/19mm/20mm等好几种，购买时需要注意。

** 压入中轴
- STEP1
和旋入中轴一样，第一步就是拆下你的牙盘，记得记清垫圈数量。


- STEP2
将中轴拆卸工具放入五通，确保边缘均匀顶住中轴

- STEP3
实际操作中要用手扶好工具，防止砸歪或损伤车架，然后在中轴上涂上锂基润滑脂或其他可用的润滑脂。

- STEP5
涂好润滑脂后用静力压入工具将中轴压入，操作时须保持让中轴和五通保持水平，如果发现角度不对则需要重新调整角度再次压入。

- STEP6
整个压入的过程应该是顺滑流畅，当旋转手柄感觉到明显阻力时，说明中轴已经
压入到位，擦去多余油脂，检查中轴边缘与车架是否接触紧密，转动轴承，看是
否顺畅，如无异样，按顺序装回牙盘链条就大功告成了，是不是很简单。
