:PROPERTIES:
:ID:       ed6786f5-f995-4c27-9c86-6bf771840d07
:END:
#+title: route

* 2004
http://bbs.casdu.cn/forum.php?mod=viewthread&tid=1084&extra=page%3D1
1、第一天：济南--淄博市
2、第二天：淄博市—潍坊
3、第三天：潍坊—平度
4、第四天：平度—青岛
5、第五、六天：青岛
6、第七天：青岛—羊郡镇
8、第八天：羊郡镇—威海
* G213
* G219
  :PROPERTIES:
  :ID:       c1282af1-df9e-40ab-ac38-0a70cd8b703d
  :END:
作者： 旺旺 原帖地址: http://bbs.casdu.cn/forum.php?mod=viewthread&tid=11571&extra=page%3D1
** 序言

 G219 线不再科普，新藏线骑行向前可延长喀什~叶城段，向后可扩展至尼泊尔、
 珠峰北坡大本营、拉萨等地。本文主要在新藏线骑行波尔攻略（ 2016 年 10 月
 27 日更新 ）－图文并茂 30 天版的基础上更新更具体的路况、行程安排、食宿、
 高程图情况，方便后期有需要的同学作为攻略参考。

 路况区别：

 1. 西藏段全程柏油路已修好，烂路主要集中在前几天的库地达坂、麻扎达坂、
    黑卡达坂上下坡途中。除黑卡达坂坡顶前最后 6 km ( K303 至 K309 ) 永久
    冻土层较长，其余多为偶然出现的小段烂路。

 2. 16年攻略存在的路碑飘移状况：叶城-狮泉河段路碑里程已重刷，与实际里程
    符合。狮泉河至拉孜段中间有部分刷白了没里程的 ( 里程碑更新到哪里记不
    太清了 )，估计下次有人去就差不多刷好了，所以实际里程碑数据跟波尔攻
    略是存在一定差异的。

** 基本情况

 1. 新藏线的难度或者说危险性主要在于：高海拔、人烟稀少导致的不可控因素
    多、大风或者其他恶劣天气，然后才是我们常规概念的每天骑行多远，爬升
    多少；另外意味着更多的负重。体能、体质的好坏，抗造与否是基础。女生
    能全程骑完，不容易；见过带女性的队伍，基本按照波尔攻略常规路线规划
    来走，也走的挺辛苦。5000 m 海拔高度对于常人来说已经是非常危险的高度
    了，所以很多人新藏线之前都有进藏骑行经历，川藏线居多；不建议第一次
    进藏就选择新藏线，除非做了足够多的准备。

 2. 高难度段主要集中在翻越麻扎达坂和黑卡达坂两座大山以及红柳滩至泉水湖
    检查站的**无人**路段，各2天行程；大高度爬升/高原缺氧/体力消耗大/荒
    无人烟等等，绝大多数有可能扎营的情况以及被迫搭车或者退出或者出现意
    外的情况基本都在这些路段。

 3. 关于大风：G219 线较为荒凉，下午三四点后多会起风。翻山阶段多近似山谷
    风。风向顺着峡谷走向由低海拔吹向高海拔，上午爬坡时顺风小，下午下坡
    时逆风很大。相对平坦路段顺风逆风都有可能。阿克赛钦盆地和青藏高原区
    风向不定，侧风居多，所以早出发早到达，吹风太多容易怀疑人生。

 4. 主要按照个人实际骑行规划来写，有较难路段会介绍备用食宿点和计划。主
    要点的食宿、洗澡、医疗、补给等情况尽量介绍。G219 线上住宿的话普通床
    位大约每人 30 CNY 左右，遇到县城或者旅游地之类的没有通铺就会提高标
    准每人 40 至 60 CNY 每人。吃饭快餐，每人 20 至 25 CNY，主要是面和盖
    饭，偶尔有15 CNY 的早餐。我们四个比较腐败，正餐能下馆子的都点几个菜
    搓一顿，每顿 150 到 200 CNY 的样子。路上以川渝菜馆为主，偶尔有湘黔
    开头的，反正都是辣。我的嘴唇后半程晒伤+干裂，受了不少罪。信号的话新
    疆境内移动要稍好于电信，3G 和 2G。我记得比较清楚；西藏境内（不含死
    人沟）电信基本 4G，再次也有 3G；移动没关心过，应该有 3G。洗澡 5 天
    左右一次。

 5. 关于小队情况，简单介绍一下方便做一些路程规划的对比和参考。开始由我
    和春全组队完成喀什 ( K100 ) 至阿克美其特段；出 K100 时春全后轴断裂
    分别返回叶城和喀什修车 2 次，我单飞库地、麻扎、黑卡三座达坂（请勿模
    仿）在三十里营房与修好车的春全会和，分别在库地和三十里营房休整一天
    等人并联系情况。后我们在去红柳滩的路上遇到另一两人小队并组团进入无
    人区，直到 G219 结束。其中春全在萨嘎县城转向中尼吉隆口岸。我们小队
    算是整个新藏线骑行过程中见到的队伍里跑的最快的一队，其他队伍里有个
    别人骑得比较快的大概也就跟全哥水平差不多。新加入的小伙分别大一大二，
    体能比我俩强。我本人的话 2017 年 11 月 至 2018 年 5 月很少骑车甚至
    很少运动，目前骑行标准功率 170 到 200 watts，耐力较好我们的实际骑行
    规划对普通路书进行了适当的压缩合并，有压缩的路段日骑行里程最长也就
    130 到 145 km 的样子，加大了难度但是并不作,7 点多基本能到，有点体力
    底子的人完成问题都不大。我全哥也就是爬坡弱一点，其他的除了偶尔思想
    滑坡都能跟得上，多休息两三分钟就等到了，队伍整体行进速度快。普通队
    伍的话常规路线也还算轻松，但是长距离的吃力不少，估计多花 2 小时。

** 日志
*** 喀什-英吉沙-莎车-叶城

 喀什算是比较常规的出发点了，主要优点在于交通方便，另外有车店，可以做最
 后一轮车辆检修和装备配置。叶城也通有铁路，如果是走中铁快运的话理论上也
 可以省略喀什-叶城段骑行，但是路上有听到自行车运不到叶城的说法，不知真
 假。也有选择 独库-沙漠公路-219 连续骑行的，就不会路过喀什了。选择叶城
 出发的话，请打包前和出发前仔细检查自己的车辆状况，请想法提高队伍的修车
 水平和车的抗造水平，比如春全的后轴断裂就是个很好的反例。

 路况基本全程柏油路，局部修路；周边戈壁，县城周边有防风林，相对舒服；剩
 下的。。真正的勇士敢于直面戈壁滩的侧风；气温较高，带好足够的水；路边瓜
 果摊及时补充能量和水分。里程大概是 喀什-英吉沙 70 km；英吉沙-莎车 120+
 km；莎车-叶城 70 km；两天行程的话基本都要有一天 190 km，有压力可分 3
 天解决，相对轻松。我和春全为了压缩时间，第一天直接喀什-莎车，192 km；
 早 8 点 30 ~晚近 11 点结束。后半程路边各种找西瓜摊续命，日饮水量大概 4
 升。喀什的时间比北京晚 3 小时，新藏线沿途点按 2 小时时差计算即可。

 第二天 莎车-叶城 相对轻松，叶城可补充最后的气罐、备用食物等。另外把水
 果当饭吃的日子马上没有了，请珍惜。几个县城有很多做生意的汉族人，安全性
 比前几年好多了，吃住超市条件都可以。住宿的话两个人住标间 100 CNY 左右
 比较划算，洗澡没问题，常用药应该也没啥问题（我们的药品喀什已全部备齐）。
 注意控制负重。我这次因为骑行后计划和个人习惯（准备单飞：即准备好所有必
 须装备）前半程确实超重了5~10 kg 的物资。另外，驼包大了（50升）还是有好
 处的，零散物品都能塞得进去。

*** 叶城-阿克美其特

 桩号：

      - 叶城        K0
      - 柯克亚乡     K62
      - 阿克美其特村 K100 海拔 2700 m

 难度一般。

 出叶城几公里就是 G219 起点，后面就是一路的缓上坡和越来越少的人烟。一直
 到柯克亚乡可以吃午饭和补给终点的话建议选择阿克美其特村，因为精准扶贫的
 政策，村委会统一组织村民接待驴友，60 CNY 住一晚外加晚餐早餐，村委会门
 口等待分配即可，每户招待 2 人，目前村委主任葛大哥是汉族援疆干部，对于
 驴友和沿途情况也都比较熟悉。阿克美其特有 3G 信号，没有电力供应，信号基
 站晚上也可能断电，有小商店。备用住宿点 K93 南京矿山宿舍，预计条件应该
 没有 K100 好。

*** 阿克美其特-库地

 桩号：

      - 库地达坂 K112    海拔 3280 m
      - 库地     K160    海拔 2950 m

 难度低，多阴雨天气。

 出 K100 不久缓坡转陡坡直到库地达坂山口；后一直下坡到K127左右（ 海拔
 2530 m )；K129阿卡孜兵站周边按理说应该有吃饭地点，但是我没找到。K129
 开始一直缓上坡到 K160 库地。库地有一个骑友之家和旁边院子里一家甘肃人开
 的旅馆。柴油发电机供电，3G 信号。

*** 库地-麻扎兵站-三十里营房-红柳滩

 桩号：

      - 道班     K204 海拔 4572 m
      - 麻扎达坂 K217 海拔 4969 m
      - 麻扎兵站 K241 海拔 3850 m

 81 km，难度大。

 出库地为检查站，K170之后基本没有缓坡了，除了爬坡，没有其他印象比较深的
 东西，麻扎达坂上坡路况尚可，下坡稍差下坡1小时左右即可到达麻扎兵站三岔
 路口，路口处一家小棚子吃住补给均有（不要学我近视没看见直接顺着大路走
 了）；2G 信号，区间供电下坡路上可以看见乔戈里峰的传言应该是假的，路边
 山头差不多。2000m爬升以及初次接触近 5000 m 海拔，难到了一多半的人。
 K204道班为常规扎营地，据说门窗完好的房间只剩一间了。另外库地~麻扎达坂
 段早晨多小雨，山顶会下雪，如果露营的话第二天注意防滑；我下午五点多到山
 顶的时候积雪已被阳光晒干，上午爬坡路上多次被路过司机提醒山顶有雪。

*** 麻扎兵站-黑恰道班-黑卡达坂-三十里营房

 桩号：

      - 麻扎兵站   K241
      - 黑恰道班   K288 海拔 4076 m
      - 黑卡达坂   K309 海拔 4950 m
      - 三十里营房 K364 海拔 3682 m

 123 km， 难度大。

 出麻扎兵站到黑恰道班为小缓坡，较轻松；黑恰道班为3日行程露营地。之后坡
 度变陡，最后 6 km 回头弯土路一般伴随着大风、过往的货车或者军车队，尘土
 飞扬，耗时较长到达黑卡达坂顶。

 下坡不久到河谷内依旧是大风；天气好的话大概率逆风，后面缓下坡速度 10~15
 km/h。我一直被吹到 K350 赛图拉哨所附近的三叉路口处（也是峡谷岔口），终
 于转成顺风（很缓的上坡），然后到达三十里营房，逆风段多花了 1 小时左右。
 三十里营房是重要的休整点，吃、住、商店都比较多，也有小诊所；有简易洗澡
 间和太阳能，不太建议洗澡，到的早水热的话就简单擦一下吧；3G 信号；骑车、
 自驾、摩托车驴友都有，也有可能碰上反骑的队伍，可提前打听下无人区段情况。

 **库地-三十里营房常规方案**

 K160 库地-K204 道班扎营
 K204 道班-K241 麻扎兵站-K288 黑卡道班扎营
 K288-K364 三十里营房

 库地和麻扎兵站搭车不算太难，尤其是麻扎兵站开店的东北老夫妻，很乐意帮你
 询问有没有可以搭的货车。没有特殊情况还是不搭为好。

*** 三十里营房-康西瓦达坂-红柳滩

 桩号：

      - 三十里营房 K364
      - 康西瓦达坂 K425 海拔 4250 m
      - 红柳滩     K486 海拔 4230 m

 122 km，难度一般。

 康西瓦达坂爬坡不陡，比较容易；下到康西瓦烈士陵园附近转为起伏+缓上坡。
 红柳滩有2G信号，食宿尚可，住宿貌似要贵几块钱。需要多备一点物资准备进入
 无人区，物价比较贵，而且几家商店差异较大。旅馆老板说 9 点后可以开电热
 水器洗澡用，不过人有点多，我们已经对洗澡没啥兴趣了。

*** 红柳滩-甜水海-泉水湖检查站-松西村

**** 第一天

 桩号：

      - 红柳滩         K486
      - 奇台达坂       K535 海拔 5170 m
      - 骑友之家板房   K594 海拔 4880 m
      - 闲置公安检查站 K636
      - 新疆西藏界     K663
      - 泉水湖检查站   K685

 106km，难度大。

 有继续前行动力者建议选择目的地为 K620 某工程项目板房。5170 m 的奇台达
 坂只是开始，后 50+ km 阿克赛钦盆地的平路才是 BOSS 波尔攻略可在K509道班
 （K511处）扎营拆分难度，因前后碰到的车友均直接翻过奇台达坂并在阿克赛钦
 盆地路段选择了向前甚至向后搭车，K509 道班是否仍具备扎营条件未知。奇台
 达坂爬坡路段开始较早且坡度较大，爬坡中间有部分平缓路段，总爬升接近
 1000m；在奇台达坂顶我们小队状态较好，还因交通管制多休息了大半小时。下
 坡很短，只有六七公里，然后开始迎接大风+缺氧+小起伏，各种荒凉。

 侧风为主，我个人因为轻微缺氧症状频频掉队。7 点多到了 K594 路牌的时候，
 大家均有不同程度疲惫，无继续前行欲望；然后骑友之家板房（K593 ~ K594马
 路右侧500m左右几个很小的板房，看到不用怀疑，真的很小）有食宿，我们一致
 决定不再前往原定目的地 K620 ；当时都觉得很明智终于找到地方睡觉了，第二
 天起来全后悔了无信号，据说 K590 ~ K594 马路上有可能收到微弱的电信2G信
 号。吃住条件都很差，米饭限量供应，我因为缺氧没吃几口。90 CNY不带早餐
 （好像还不带晚餐？）狼群多发地，晚上一定用砖头堵好门；不要单独出门上厕
 所，互相望风；前半夜风很大，板房门口有不少废弃可用的气罐。甜水海地区不
 到 4900 m 的海拔硬是能睡出 5500+ m 的感觉，各种睡不好，早上均有不同程
 度头痛。

 备用住宿点：

 1. 甜水海旧兵站，据说在路边，我真的没怎么注意到位置；据骑友说多数已经坍塌，不太具备扎营条件。

 2. K620 某工程项目部板房，在 K620 路牌附近左侧 2 km 处；铁丝网上开了一个口有一条过去的小路，晚上不亮灯的话可能真的找不到位置。K620 处有 2G 信号，可提前在红柳滩处咨询老板在不在家（K620 和 K594 均有偶尔不开门的可能）。到了 K594 路牌处（K594路牌之前是一个弯，之后路线较直）还有余力且风向合适的话，优先建议选择 K620 食宿，一路平路，条件应该比 K594 好不少。从 K620 开始，可以看到一点绿色了，野生动物也开始增多。

 3.甜水海新兵站，也需要从马路进去几公里，成功率极低，不建议尝试。

**** 第二天

 桩号：

      - 闲置公安检查站 K636
      - 新疆西藏界     K663
      - 泉水湖检查站   K685

 92KM，难度一般。

 海拔整体上坡，很缓，所以今天路程平均海拔也有 4900+ m。 过了红山湖后有
 一段爬坡，最高点红山湖垭口（ 海拔 5200+ m ）没有明显坡顶的感觉，然后缓
 下到泉水湖检查站（死人沟海拔 5150 m）

 检查站门口一家小板房有7张床位，条件略艰苦；提供泡面，太阳能电池板供电，
 电信2G信号，信号较差。老板提供的热水泡个面就行了，饮用水建议自己烧或者
 喝凉的矿泉水；不信的话可以尝试下。晚上运气好可看到清晰银河，野狗较多，
 没事别乱跑。比起甜水海，起码还能睡得着，早晨轻微头痛。

**** 第三天

 桩号：

      - 死人沟    K685
      - 界山达坂  K700 海拔 5348 m
      - 龙木措    K718
      - 松西达坂  K728 海拔 5248 m
      - 松西村    K742 海拔 5240 m

 57 km，全程海拔 5000+ m，难度较低。

 有野心的同志可直接松西吃完饭杀到多玛乡出死人沟，先是平路，然后几公里上
 坡到界山达坂。界山达坂下坡到龙木措（湖面海拔约5000）湖边，途中有一小段
 上坡。龙木措一直上坡到松西达坂，再过一段起伏路就到松西村了。

 松西村：海拔较高，氧含量尚可，睡着比无人区强；两家家庭旅馆十几张床的样
 子，有补给。吃的话还是可以炒几个菜的，毕竟高海拔，没那么丰富，太阳能电
 板，电信4G信号。到了松西，恭喜你新藏线最难最艰苦最虐的路段已经过去了，
 后面的只要不作基本没什么大难度，可以趁着4G网朋友圈吹起来了。

*** 松西村-多玛乡-日土县-狮泉河

**** 松西-红土达坂（ 海拔 5380 m ）- 多玛

 99 km，难度一般

 过了松西开始，我就很少看路碑了；今天会过新藏线最高点红土达坂，只有200m
 左右的爬升，所以其实很简单。出门11km左右到顶，然后一路缓下坡到多玛乡；
 注意保暖。多玛乡可腐败，住宿稍贵，各种档次都有；洗澡还是奢求（印象中有
 一家一周只开一次的澡堂，忘了是多玛还是日土县了）,也不差这一两天了。有
 乡卫生室, 有果蔬店，有大型超市；最重要的有邮局，下午约4点半到6点半开门，
 可以把用不到的露营装备通通打包发走。多玛的邮局也是揽件后每周末来一趟车
 拉货的，所以时间上不如后面的日土县和狮泉河快，对时间有要求的建议后面到
 县城发快递。

**** 多玛-日土县

 102km，难度一般

 出多玛大概有 20 km 缓上坡，爬升200多米，然后一段缓下坡+起伏路面,约 65
 km 就可以看到班公错了。沿湖骑行一两公里就有比较方便下到湖边的地方，想
 完成新藏线第三件事“班公错里洗个澡”的同志可以下湖了，后面的路跟湖边都有
 高差，印象中没有太合适下湖的位置。80+ km 有一处大的观景台，适合各种拍
 照；过班公湖后约10 km 就到日土县城了。日土县城住宿较贵，可洗澡的标间均
 在200+，三人间之类的床位也要40+.刚到县城是老城区，可以直接出国道拐进去，
 有相对便宜点的住宿。

**** 日土-拉梅拉达坂-狮泉河

 125km，难度稍大，半程结束

 出日土缓坡+平路约 75 km，然后开始爬拉梅拉达坂。虽然坡顶标了5191 m 的海
 拔，不过实际上貌似也就不到 4900 m，爬升 600 m 左右。从拉梅拉达坂可直接
 下坡到狮泉河；过了拉梅拉达坂，基本每天都要淋雨。狮泉河作为阿里重镇，
 G219 最大城市当之无愧；吃喝玩乐快递医疗都有，可以休整半天或1天。住宿较
 贵，住便宜的可以去澡堂洗澡，该好好洗洗了。可凭身份证去阿里旅游局领新藏
 线骑行证书，地址：马泉路和滨河南路岔口向南 200m 左右，地图基本查不到；
 微信公众号：阿里旅游可补办边防证，只能补阿里地区各县的；不在派出所，统
 一在葛尔县政务服务中心西侧窗口由边防人员办理。

*** 狮泉河-巴尔兵站（索堆村）-塔尔钦-霍尔

 札达土林、冈仁波齐、玛旁雍错（以及旁边的鬼湖拉昂错和中印边境纳木那尼雪
 山景观）都是阿里热门景点，想去的同志提前做下攻略。

 狮泉河-塔尔钦常规路线：可两天半或3天完成

 狮泉河-那木如                       76km
 那木如-巴尔兵站（索堆村）-门士乡     118km
 门士乡-塔尔钦                       52km

 压缩路线：
 狮泉河-索堆村                      135km   难度稍大
 索堆村-门士乡-塔尔钦                113km   难度一般

 那木如和索堆村均有去札达土林的路可包车，那木如稍远。我们去的时候那木如
 的那条路在修路，索堆村相对近一些，包车 150 km 600 rmb，想试试运气搭车
 也可以，得早到，压缩版路线基本不要抱希望。去扎达土林的话计划好时间，应
 该会有半天空闲，也可逛下札达县城。然而我们杀到索堆村大家都没什么兴趣过
 去。

 印象中出狮泉河过了昆莎机场路口几km的样子路边是有一个小村子有茶馆可以吃
 饭的，记不太清了。索堆村住宿茶馆和大帐篷，条件算是后半程稍差的了，吃的
 还可以。门士乡可吃饭。住宿塔尔钦旅游热门地点，超市药店等齐全，住宿、补
 给较贵。

 到了塔尔钦，冈仁波齐还是要转的，全程 49 km 山地徒步，路况较好，路迹明
 显，人很多。塔尔钦 海拔 4700 m 左右，徒步最高点垭口海拔 5640+ m，这个
 高度还是会有轻微缺氧的可能，比如我全哥最后 200m 爬升又双叒叕掉了，当然
 了凭借耐力后半程成功拉爆回来，一雪前耻。早出发一天完成的话，可以尝试下
 逃票，出镇的口还没上班，主要是回来的口检查，我们四个人成功率50%，总结
 下原因回来的太早，天还没黑；哪怕晚20分钟赶上那场冰雹也能混过去。一般路
 线2天完成，爬坡前的寺庙和下山途中各种帐篷均可住宿，有泡面。

 雨雪冰雹等神山的洗礼很热情，无长距离徒步经验者强烈建议出门右手小商店买
 根登山杖，这几个货说了好几遍不买，最后 20 km 抢着用我的。

**** 塔尔钦-霍尔乡  42km

 休闲骑，主要放松下转山已废的腿和膝盖，高程图略过；天气好的话可以回头看
 看神山。霍尔乡住宿挺便宜的，傍晚可去玛旁雍错附近溜达下，约 7 km，土石
 路，风比较大；当然了也是要收费的（再次吐槽当地政府），我们就在旁边非收
 费区的某土坡上看了下，天气不好，湖水效果就差一些。

 第二天早晨起床在镇上就可以看到高清版纳木那尼，出霍尔乡在马路上拍的相对
 耐看。果然水还是有阳光才好看——来自雨季各种阴雨天看山看湖以及深圳看海的
 血泪经验。

 据其他车友说玛旁雍错骑车转湖 90+ km 路况较差，石头多，走的人应该挺少的。

*** 霍尔-马攸木拉检查站-帕羊镇-老仲巴
*** 老仲巴-萨嘎-切热乡-桑桑镇-拉孜查务乡
*** 拉孜查务乡-白坝-珠峰北坡大本营
*** 拉孜-日喀则-江孜县-浪卡子县-拉萨

** 注意事项

 1. 不管这条线再怎么吸引你再怎么有挑战，请在考虑要不要去之前务必有长途
    骑行经验和高原活动经验，然后才是怎么去的问题。

 2. 对自己和整个队伍体能和体质有足够信心和准备的人可以选择不带帐篷/防潮
 垫/睡袋等物品以便减重；这只是一个提议，不要盲目效仿。此次骑行我只在
 K594 板房因为条件太差睡了一次睡袋，帐篷/防潮垫均没有用到过。假如露营的
 话，计划实物是榨菜+馕+白开水。因为一路没有露营，带的气炉和气罐只在甜水
 海和死人沟各烧了一次白开水。有食宿的地方开水供应是没啥问题的，也可以选
 择不带气炉气罐和小炊具。气炉不让运输，在叶城县乔丹户外店有卖。南疆安检
 比较频繁，买到了也别大摇大摆拿在手上，容易说不清。小罐还是大罐根据队伍
 情况预估，不频繁露营做饭的话两三个人小的（ 230 ml ）足够了。

 3. 尽量不要单飞，尤其是无人区路段。G219 前半段全程有狼活动，人烟越少也
    就是我们骑得相对艰苦的那几天狼的活动范围越大。天黑前务必赶到目的地
    或露营地，如果不能的话，请尽早预估并拦车搭车，哪怕是拦到回头车，也
    不要在天黑后野外活动，一定要在密闭的空间里露营！

 4. 尽早出发，下午基本会起大风；另外预留时间应对突发状况

 5. K100~甜水海 需翻越四座达坂，道路依山体而建时，一定注意周围的滚落石
    声音，尤其是雨天或雨后，及时规避。道路上落石挺常见的。

 6. 快递

 7. 边防证

** 装备
*** 气炉气罐

 气炉就是淘宝常见气炉，关键词户外/便携/防风等，气罐接口处最好是螺纹款的，
 兼容性好一些。另外，气炉的电子打火装置在飞机上属于禁运品。计划装备随飞
 机托运的同学请注意。

 气罐就是脉鲜高山罐，橙红色这种，叶城可买到 230 ml 和 450 ml 的，螺纹接
 口常见，燃料是丁烷。

** 野外
*** 狼
 正常人是没胆像电影七十七天里那样硬刚的，另外严格的说，任何帐篷都是挡不
 住狼的，包括用自行车堵开放门口之类，16年以前有太多露营户外遭到狼袭击的
 事故，所以不要侥幸。所以正常人都比较怂的选择了怎么防止碰到狼或者被狼盯
 上，即注意事项里提到的一定不要夜间在野外活动，露营一定要选择密闭空间。
 白天碰到狼的概率很低，即使碰到了绝大多数也是独狼或者双狼出来放风的；很
 少出现白天狼攻击人的行为，毕竟 G219 上还是有车辆往来的；但是白天尤其傍
 晚看到狼的话，请再三确认你今晚能不能赶到目的地（ 准确的说是合适的居住
 地 ），否则晚上你可能面对的是群狼。
* 傥骆
** 第一天  $HOME  - 盘龙乡
** 第二天  盘龙乡 - 黄柏源
** 第三天  黄柏源 - 钓鱼台村
** 参考资料

迷雾傥骆道: http://www.dili360.com/article/p5350c3da6a2ec39.htm

 #+begin_quote
 傥骆道是穿越秦岭的几条千年蜀道中唯一一条基本保持原貌的。别的“难于上青
 天”的路，不是成了公路，就是铁路，支离破碎，有一段没一段，很难找到当年
 的风貌。天堑变通途当然是好事，无数桥梁和隧道穿越其中，眼一睁一闭，秦
 岭就这么翻过来了，再问你这秦岭什么样，可能也就是恍惚的印象了，有意思
 吗？整天待在城里腻歪了，总觉得还是老老实实用脚量一量比较过瘾，那么就
 走吧。 -- 周本州

 屈伸八十里，凡八十四盘。 -- 《读史方舆纪要》

 我沿着傥骆道走了一段，就觉得此道不仅是曾经的交通要道，而且是生活之道，
 传统之道。 -- 《远山古道:秦岭行走笔记》
 #+end_quote
* other
** most boring one，Region,Saskatchewan
   https://youtu.be/YaPa4esJJx4?t=107
** Cross the Bering Strait

 The closest official port to the Bering Strait in Russia’s Far East
 is Providenia. The distance across the Bering Sea from Alaska to
 Providenia is 400 km. This stretch is broken by St. Lawrence Island
 (American) which lies 200 km out from Alaska. The island is 125 km
 long, and it is 75 km from Russia.

 A crossing via this route would necessitate the ability to navigate
 200 km of open stormy water. It is also necessary to receive
 permission from the Russian government to arrive in Providenia in a
 small boat (a process which takes about a year).

 Ref: https://angusadventures.com/adventurer-handbook/beringstrait/
*** Nome-to-Provideniya route

 ref: https://www.rome2rio.com/map/Provideniya/Nome
