:PROPERTIES:
:ID:       d3f69716-d902-4ac5-984c-ccc9b4b716e5
:LAST_MODIFIED: [2021-08-07 Sat 13:57]
:END:
#+TITLE: casdu-bike-standard
#+CREATED:       [2020-10-30 Fri 12:07]
#+LAST_MODIFIED: [2021-08-07 Sat 13:57]
#+filetags: casdu

* 远征车标准

- 以车架为核心，包括前叉、把立、把横、座管、座包、曲柄、脚踏、轮组在内的承重部件不得使用碳纤维部件或非正规厂家生产的无标部件。

  原因：远征路上发生事故（非常规摔车）的可能性较大，碳纤维部件在损伤后直接断裂，铝合金部件可以支撑到休息点进行更换。

   (do we have a log of previous broken parts on bike?)

- 对轮径和内胎气嘴不做特殊要求，外胎必须使用越野胎（700c要求宽度28以上越野胎），不得使用光头胎、真空胎和管胎。常规轮组单侧辐条数量不得少于12（高端山地轮组维修难度大，亦不建议使用）。除26寸轮径外的规格，需要自备内胎*2、折叠外胎*1、驱动侧与非驱动侧辐条各2

   (length of spoke?)

  原因：远征可能存在碎石路段，要求轮胎抓地力良好。雨骑中要求轮胎不打滑。颠簸路面要求轮组耐受性好，辐条不松动不断裂。

- 不要求前叉具有避震功能，因此牺牲的舒适性自负。

   (how to change fork?)

- 常用把位高度不得低于座包，一般骑行姿势，上身前屈不得超过45度，不得小于15度。（数据未经校核）

  原因：把位过低对腰部负担过大，身体直立则臀部压力大，且重心偏高不利于控车。长途骑行中两者都很致命。

   (what is the best position riding long journey > 30 Days)

- 远征车必须能够装载后货架及驮包。

  原因：远征路上不仅要携带自己的东西，也要为大队装载一些物品。长途骑行中，背包对肩有很大压力，不建议使用

   (I personally suggest using metal)

- 刹车类型不做要求，但必须保证前后两个刹车有正常的刹车力度，单刹车辆禁止上路。

  原因：单前刹存在翻车风险，单后刹则制动力不足。

  (if dis-brake possible, please do it; bb5 is good enough)

- 车辆需装载脚撑，摆车必须整齐

  建议使用较宽的脚踏，不可使用锁踏

  (I personlly suggest MG1)

- 变速系统需保证正常使用，不跳链

  (At least m390)

- 特殊车辆

  (what are they?)
