:PROPERTIES:
:ID:       17a7c446-984c-4dc5-b073-2017080fdf1d
:LAST_MODIFIED: [2021-08-07 Sat 13:57]
:END:
#+TITLE: casdu-bike-bearing
#+CREATED:       [2020-10-30 Fri 11:50]
#+LAST_MODIFIED: [2021-08-07 Sat 13:57]
#+filetags: casdu

* videos
** analysis on White T11 Rear hub
https://www.youtube.com/watch?v=xnJthHwrLDc

* 轴承花鼓 (a.k.a 培林花鼓?)

* 滚珠花鼓

滚珠花鼓，不管是禧玛诺妇科龙还是普通低端的，结构都差不多，只是加工精度不同，再是禧玛诺家的防水结构做的十分优秀，滚珠的精度足够高，从结构来说，确实滚珠花鼓的结构在承受轴向力的方面理论上来说更优秀，然而，就我个人经验来说，我见过的大部分禧玛诺花鼓，第一，磨损问题严重，就是为了转动顺畅，很多人在没有足够经验的情况下会把对锁螺丝调的过松造成匡量或者对锁螺丝过紧，匡量或者过紧就会造成滚珠磨损加快，珠碗和轴出现麻点，转动不顺畅，然后就代表这个花鼓的很多结构需要更换。淘宝一看修补件价格，对不起打扰了对不起打扰了，起码我不太能接受。 散珠花鼓成为一次性使用产品，那这个成本自然是不太能接受了（尤其对山地车这种使用情况更恶劣的花鼓来说）

> by Mr.k

> 下面我就说我个人的意见，对于咱来说，为啥我觉得轴承的花鼓要略好于滚珠的花鼓，耐用性，轴承花鼓一般不会让你微调对锁螺丝，就算有的话，也不存在调整游隙过差而导致磨损严重（其实滚珠的轴承算要靠自己调整游隙，而深沟球轴承的话就是出厂游隙已经定下来了）。并且，一个很重要的一点，在理论上来说深沟球轴承本身除了径向载荷，设计就允许部分轴向载荷，说摇车发软的，应该不太可能是花鼓的问题。

* replacement

换轴承吧，由于我前轮出现转一圈有麻麻的震动感，轴承补加润滑油也没有效果，遂决定更换。只需要一个轴承拉玛工具，一个橡皮锤就能搞定，步骤极其简单，确定轴承规格，买新的，工具把轴承拉出来，两边都拉出来，注意旧轴承要保留，因为一会锤进新轴承要用，然后拿旧轴承垫着新轴承，橡皮锤均匀敲进去即可，步骤简单，效果极棒。最后一，这个拉轴承工具我就收着了，有人需要动手换轴承可以和我要。

> by SK

> 装轴承要求更高一些，都买了轴承拉马了，就直接再买套静力压入轴承的工具吧，不贵. 拆的话直接砸出来没啥问题，装用砸的精度保证不了容易有异响.

> by WB

> 对于装轴承，其实对好位置然后用螺丝直接拧紧的过程中，就会把轴承自己压进去了，感觉还是挺好操作。
