:PROPERTIES:
:ID:       ae87369d-fabd-4b63-aa73-2eac339506e3
:END:
#+TITLE: casdu-120
#+CREATED:       [2020-10-30 Fri 12:04]
*+LAST_MODIFIED: [2020-10-30 Fri 12:04]


* Useful reference:
** https://www.solowfa.com/online-course.htm
** courses: https://www.udemy.com/course/first-aid2/
** https://www.redcross.org/content/dam/redcross/training-services/no-index/First%20Aid-CPR-AED-Participant's-Manual.pdf
** https://www.redcross.org/content/dam/redcross/training-services/no-index/WRFA_PocketGuide.pdf
* 不要做
- 红药水含重金属汞，并且不能与碘酒碘伏同时使用！
* 突发事件应对 （预防和处理）
* 疼痛与不适
* 擦伤与外伤
轻度擦伤 创口擦破皮，有红肿、淤青，不出血或出血很少，一般及时涂上碘伏或紫药水（不过紫药水有收敛作用，易使伤口处结痂变干；红药水含重金属汞，并且不能与碘酒碘伏同时使用！），自然风干比较好，但别让伤口沾到水。

[TODO]红药水?

重度擦伤 要先止血。一般指压近心端，冷敷也是很好的方法（血管收缩，止痛），用清水或生理盐水直接冲洗创口，将沙土、血块等异物冲去。冲洗中可用医用棉签轻轻将创口的异物刷去。再用双氧水或75%酒精消毒，彻底清洗伤口。用碘伏也可以，但不要用紫药水等颜色深的药物，会渗透到皮肤里。

[TODO]轻重如何区分？或者说什么是重擦伤？

** 双氧水的使用

（1）可先用饮用纯净水冲洗伤口及伤口的周围部分，使伤口部位没有多余的血迹和尘污。

（2）再用棉签清理伤口及周围的水迹和血迹，最好先用一根棉签轻轻擦拭伤口一次后再清理第二次，一定要让伤口在用药之前处理干净（异物会导致伤口化脓）。

（3）按伤口大小在伤口表面上倒洒上双氧水，再用干净的棉签轻轻擦拭伤口及伤口周围部分涂匀，使双氧水遍布整个伤口及伤口周围。

（4）双氧水作用于伤口时呈泡沫状，此时不要擦除它，等待它慢慢氧化殆尽。如果伤口会流出少量透明粘稠的液体时不要擦掉它，因为那是人体自身免疫机能分泌出的组织液，是辅助伤口恢复及消炎的一种液体，如果分泌过多可以适当的擦掉。

  严重的话或者天气较凉时可以用干净透气的纱布包扎，但伤口结疤后就不要用绷带或纱布掩盖了，毕竟夏天出汗多，易感染。必要时可服用消炎药。伤口包扎大多用到敷料，就是用于覆盖疮、伤口，吸收渗出液和有毒物质并防止外部细菌进入的透气材料。关于敷料的选择，在开始几天伤口主要是肉芽组织的生长，需要比较湿润的环境，所以开始几天敷料可以多用几层，保持创面的相对湿润。一般使用生理盐水纱布覆盖创面，但细菌在潮湿环境下 6-8 小时就会进入对数增殖期，故对于感染严重的创面，要作到勤换药（最好3-4次/日）。凡士林纱布可以提供潮湿的环境有利于创面的肉芽生长，并可以减少组织液的渗出，早期的创面还可以止血，但对于感染严重的创面要慎用，因其易因为引流不畅，常加重感染。而到了后期，伤口的生长主要是角质的生长，此时创面需要相对干燥的环境，所以敷料就应该在起到隔离作用的前提下尽可能薄。换药常用药品有等渗生理盐水、3%---10% 生理盐水（有较强脱水作用，用于肉芽水肿明显的创面）、3% 双氧水（尤其适用于厌氧菌感染的伤口）、0.02% 高锰酸钾溶液（用于洗涤腐烂恶臭、感染的伤口，尤其适用于疑有厌氧菌感染、肛门和会阴部伤口）。

* 扭伤
多见于脚踝和腰部。运动前先活动一下脚腕手腕，甚至体训的内容来一遍也可以。选择适合的鞋子，鞋底不要太软。骑车尽量不要猛然发力。再就是平时加强小腿与足部肌肉训练，增强关节稳定性。最重要的，要有正确的骑行姿势，对腰部有很好的保护作用。

立即停止活动以减少内部深层损伤，并用冷水冲洗局部或冰块冷敷扭伤部位。冷敷时不要推拿或按摩。然后用绷带或三角巾包扎，不必过紧，局部固定即可。冷敷最好是加压包扎，一次半小时左右，看看是否还肿，若有必要再反复进行。24至48小时后，可以用温热毛巾热敷，或轻轻按摩来消肿，热敷时间不要太长。休息时要将患处垫高。

* [[

歇了很久突然骑车或一次长途骑行很容易发生抽筋。骑行前压压腿，做一下伸展运动，要活动开。尤其爱抽筋的，一定不要嫌麻烦偷懒。骑行中可以慢慢增大强度，保持节奏（踏频）。补充水分和电解质！抽筋发生还有一种原因，就是体内钾钠不平衡，盐分大量流失，负责放松肌肉的钠离子减少。淡盐水是成本最低的啦，像爬药乡这种消耗如此之大的活动，一定记得补充盐分。

抽筋后，办法就是拉伸抽筋部位。手指：抽筋的手先握拳，然后用力伸张打开，重复做。

手臂：抽筋的手先握拳，再将小臂屈肩，然后伸臂伸掌，重复动作，至复原为止。

腹部：将上身舒展轻轻向后弯，拉直腹肌。
小腿：用手握住脚趾用力后拉，另一只手向下压住膝盖让小腿伸直。

大腿前面抽筋时，把手腕放在膝盖后方，将腿往后弯曲，使大腿前面拉直。最简单就是蹲下。大腿后面抽筋时，站直，可下压。

这些动作都要轻轻地做，另外，抽筋了就休息一下。抽筋说明你的运动量已经超过了你的身体所能承受的负荷。
* 中暑与脱水

尽量在阴凉的地方骑行、活动；长时间运动一定要多补水和电解质，并注意休息。炎热环境下骑车前半小时服用藿香正气水。有时中暑的队友只是觉得自己有点难受，意识不到已经中暑了，但中暑有比较明显的外在表现，队长或队友在夏季骑行时要多关心身边的人。由轻到重大致有这几种表现：面色潮红，皮肤灼热；四肢尤其是小腿后部肌肉痉挛；头痛、头晕、呕吐，面色苍白、皮肤湿冷、手足抽搐。

迅速到阴凉通风处，用冷水擦拭脸部和四肢，有条件就用冰袋冷敷一下。人丹、藿香正气水自然必不可少，还可用清凉油、风油精涂擦太阳穴处。然后缓慢饮用冰盐水或清凉饮料，饮水一定要少量多次，大量饮水会影响本来就很虚弱的脾胃，还可能造成痉挛。中暑后饮食要清淡，也不可多吃生冷瓜果。一般如果处理及时，4小时左右就可恢复啦。

这里再顺带提一下脱水。呕吐、高烧、出汗、腹泻或缺乏水及食物都会导致严重脱水症。脱水按细胞外液的渗透压不同可分为三种类型。以失水为主者，称为高渗（原发）性脱水；以失钠为主者，称为低渗（继发）性脱水；水、钠各按其在血浆中的含量成比例丢失者，称为等渗性脱水。明白了机理，就可以根据情况为队友补水或补盐。脱水是紧急的状况并且可能致命。一般的症状是极度口渴（患者可能无法解渴）、疲倦、头晕、腹部或肌肉痉挛。处理方法：1.将患者移到阴凉处。 2.补充损失的体液和化学物质，绐患者水、茶、运动饮料或清汤 3.如果症状持续或其他并发症（如呕心、腹泻）出现，就要看医生。

* 流鼻血
注意防暑、补水，避免撞击头面部。

出血的部位90%位于鼻中隔的前下方---基歇尔巴哈部位。（好吧不多解释，如图）此处的粘膜极为薄弱，而且满布丰富的微血管，因为靠近鼻孔，一受到外力或遇上感冒或鼻炎所引起的鼻黏膜敏感便很容易引发血管的破裂。

大家小时候可能都有过流鼻血头向后仰然后拿卫生纸塞起来的经历······其实不太科学。流鼻血后最好采取坐位，头稍向前弯，即使血流到口腔也不要咽下，因为容易刺激胃粘膜引发呕吐。 少量出血时可指压止血：将鼻翼压向鼻中隔，（鼻正中间的软骨是也）或鼻腔内填塞局部止血剂再行压迫。可以用冷毛巾、酒精棉冷敷鼻根部，但如果出血较多，可以用纱布条或棉花条卷紧填塞鼻孔，滴麻黄素；或进行头部冷敷。出血后就不要吃过热、过硬食物了。

还有一点要注意，有时鼻子出问题可能是内部损伤的反映。由外伤引起的出鼻血既而引发耳中出血应及时送医院。若外伤引起鼻腔流出水样液体（近似透明，掺有少量血丝，无异味），这是脑脊液，说明颅底有骨折。应任其流出，并急送医院。堵塞鼻腔反而容易引起颅内的细菌感染。

* 眼中进异物
如果是小飞虫，它很快就会死去了，一般也不用揉，人眼受到刺激会自己流泪清洗，它就随泪液出来了。其他沙尘等异物，如果泪液不能冲出来，另一个人可以用手指（手指一定要先清洗干净）轻轻向前上提起上眼睑，对着眼睛轻吹气刺激流泪；不奏效就直接查找异物，让病人先向上看，翻开下眼睑查找，没有再找上眼睑。找到了要用干净纸巾毛巾一角或消毒棉签将异物沾出。最严重的情况，以上都不行，就用生理盐水或3％硼酸水冲洗，棉签轻轻擦去，滴抗生素眼药水。眼睛是娇贵的器官，有什么问题应尽快与医务人员联系啊。最后，如果找不到异物，但总有异物存在的感觉，可能是刺入角膜了。先用纱布包一下保护好，再去医院处理。

但有一点，如果生石灰入眼，不能揉也不能直接用水冲洗。（后果严重，都懂···）先用棉签或手绢一角拨出石灰粉，再用清水反复冲洗，至少15分钟。然后去医院治疗。

[TODO]路上会遇到吗？如何识别？

* 运动性晕阙

在运动中或运动后一时性知觉丧失，称为运动性晕厥，它是由脑部突然缺血所致。平时缺乏锻炼者，突然参加较大运动量的锻炼，心脏机能一时跟不上运动需要，会造成血液回流量减少，心输出量也随之明显减少，因而出现暂时性脑缺血。若机体对这种情况的适应能力较差，便更容易发生晕厥。

新队员拉练时一定注意运动强度······呼吁大家平时加强训练。

症状：先是全身乏力、头晕、耳鸣、眼前发黑、面色苍白等，紧接着失去知觉，突然倒地，出现手足发凉、脉慢而弱、血压下降、呼吸缓慢、瞳孔缩小等症状。清醒后仍会有头昏、精神欠佳、乏力等感觉。有前驱症状时，就应下蹲或卧下休息片刻，可避免发生昏倒。已晕厥的应使其平卧，头低足高，解松衣领，注意保暖，下肢作向心性揉推按摩。或及时指掐或针刺人中、百会、合谷等穴位。一旦停止呼吸了，要立即送医院，或在救护车到来前做人工呼吸（见第三部分），此时头要转向一侧，注意防止痰液或呕吐物阻塞喉头。

* 起痱子

在高温闷热环境下，出汗过多，汗液蒸发不畅，汗管容易堵塞、破裂，汗液外渗入周围组织，就会长痱子。主要表现为小丘疹、小水泡。因为瘙痒而过度搔抓可致继发感染（所以不要抓搔，用药），发生毛囊炎、疖或脓肿。预防嘛，中途休息时把袖套，头巾等方便摘下的摘一下，每人自备一条小手巾，打湿后将皮肤仔细擦拭，作用为降温排汗，保持汗液蒸发顺畅~平时注意皮肤清洁，勤洗澡，保持皮肤干燥，穿宽松透气的衣物。

治疗痱子最有效的方法是呆在凉爽的环境中（长途骑行的话可能没有这个条件···），加强室内通风、散热，穿衣宽松，清洗后可外扑痱子粉，也可外用炉甘石洗剂、糖皮质激素。洗澡一定用温水！脓痱可外用抗菌药膏，严重时应用抗菌药物。但要避免使用油膏（若是得了痱子，为防止阻碍汗液蒸发，建议那个部位就不要再涂防晒霜了，其实还是多使用防晒的护具较好）。

* 晒伤

即使出现水泡也不要去挑破，用冷水毛巾冷敷。

* 食物中毒

会恶心、呕吐、腹痛、腹泻，往往伴有发烧。吐泻严重的还能发生脱水、酸中毒，甚至休克、昏迷等症状。这时首先应立即停止食用可疑食物，同时立即拨打120呼救。在急救车来到之前：1.催吐。对中毒不久而无明显呕吐者，可先用手指、筷子等刺激其舌根部的方法催吐，或让中毒者大量饮用温开水并反复自行催吐，以减少毒素的吸收。如经大量温水催吐后，呕吐物已为较澄清液体时，可适量饮用牛奶以保护胃黏膜。如在呕吐物中发现血性液体，则提示可能出现了消化道或咽部出血，应暂时停止催吐。2.导泻。如果病人吃下去的中毒食物时间较长（如超过两小时），而且精神较好，可采用服用泻药的方式，促使有毒食物排出体外。3.保留食物样本。确定中毒物质对治疗来说至关重要，因此，在发生食物中毒后，要保存导致中毒的食物样本，以提供给医院进行检测。

* 水土不服

初到一个地区，自然环境和生活习惯发生改变，正常情况下与人共生彼此互相依赖制约维持人体生态平衡的菌群在种类、数量、毒力等方面都会发生变化，可能造成有害菌的入侵，益生菌的减少从而引发系列不适，这在医学上叫“菌群失调症”，尤以腹泻最为常见。还可能出现食欲不振、腹胀、腹痛或女生月经不调等。水土不服而引起腹泻常常是饮食上出了一些问题，比如：
1．饮食受到病毒如轮状病毒，细菌如大肠杆菌（最常见）、志贺氏杆菌、沙门氏杆菌、金黄色葡萄菌，寄生虫如梨形鞭毛虫等的污染。
2. 饮食无节制。
3. 食物过凉或过热、营养不均衡等。远征要走过很多地方，大家路途上一定注意照顾好自己。

如果腹泻：
1.多喝水 2.补充电解质 3.避免乳制品及固体食物 4.使用止泻剂 5.请教医生服用抗生素 6.旅行时避免未煮熟的蔬菜、肉类、海鲜及不洁的饮料 7.确保餐具清洁 8.将水煮沸三至五分钟后再饮用 9.多喝可乐、柳橙汁等酸性饮料，有助于抵制大肠杆菌的数量。最先要的还是吃点藿香正气丸，或藿香正气水，疗效显著。


初到外地时，如果身体不适，不妨采取以下措施：第一，睡前饮用蜂蜜。中医认为，水土不服的发生与脾胃虚弱有密切关系，蜂蜜可以健脾和胃、镇静安神~而且，因环境改变引起的肠道菌群失调，还可能引起便秘，适当饮用蜂蜜也是不错的办法。第二，常喝茶。茶叶中含有多种微量元素，可以及时补充当地食物、水中所含微量元素的不足；茶叶还具有提神利尿的作用，能加速血液循环，有利于致敏物质排出体外，减少荨麻疹的发生。（这个可能条件不允许···）第三，品尝“风味特产”要适量，多喝酸奶。酸奶中的乳酸菌有助于保持肠道菌群的平衡，能最大限度避免胃肠道紊乱诱发的腹痛、腹泻等不适。如果不慎出现了腹胀、腹泻，必要时可服用吗叮啉或黄连素片，恶心呕吐者可服胃复安。第四，很多人还会出现咽喉疼痛、口腔溃疡、鼻出血、便秘等“上火”症状。不用担心，尽量保持原有的生活习惯，正常作息，多选择与原来口味相近的食物，少食辛辣，多吃清淡的果蔬及粗纤维食物；多喝水。

* 起水泡
因磨损、重压、烫伤、冻伤等引起的体液渗出易形成水泡。起泡后（未破）要先用肥皂清洗干净。然后把别针等针头用火烫消毒，刺破水泡。最后用干净的纱布将泡中的积液轻轻挤出擦干，最后贴上护创膏。若泡已经被磨破，一定先消毒再进行处理。

* 电焊光伤眼

不戴防护眼睛看电焊弧光，眼睛会被电弧光中强烈的紫外线所刺激，可能发生电光性眼炎，主要症状是眼睛疼痛、流泪、怕光。从眼睛被电弧光照射到出现症状，大约要经过2-10个小时。电光性眼炎如果继发感染，而造成角膜溃疡，好后也会有角膜薄翳而影响视力。所以要重视处理方法。应急措施是用煮过而又冷却的鲜牛奶点眼，可以止痛。开始几分钟点一次，而后随着症状的减轻，间隔时间可适当地延长。还可用毛巾浸冷水敷眼，闭目休息。经过应急处理后，除了休息外，还要注意减少光的刺激并尽量减少眼球转动和磨擦。一般经过一、二天即可痊愈。严重的话用4%的奴夫卡因药水点眼，迅速到医院就医。（奴夫卡因就是盐酸普鲁卡因，是一种局部麻醉药，可用于浸润麻醉、腰麻、局部封闭止痛）

* 叮、咬伤

被带有毒腺的毛虫刺伤后，伤部即变红肿，并有痛感。可用手挤出毒汁，并用肥皂、自来水擦洗干净。

被蝎子、毒蜘蛛等叮咬要首先判断伤口是否有毒，有毒情况下可进行近心端包扎，静卧。无毒用碱性（如肥皂水、氨水）冲洗伤口。蚂蟥毒素是碱性的，两面针的牙膏效果好；可以局部涂醋，清凉油等，或用中性的药水中和。


蜜蜂叮咬后处理方法如下：用镊子或针过火烧一下，挑出蜂刺,切勿用手去挤压伤口的刺。 蜂毒属于微酸性,可使用肥皂清洗患部，用沾肥皂水的毛巾敷于患部5~10分钟,以中和毒液。冰敷可以减轻红肿疼痛。若被刺后２０分钟以内无异常反应，一般说问题不大。严重者送医院治疗。特别地，黄蜂毒液呈碱性且较大，进入人体后可引起过敏性休克、急性肾功能衰竭。万一不慎黄蜂叮咬，可用棉花蘸柠檬汁轻拍伤口，或用醋、稀释的醋酸、硼酸冲洗，严重者应立即到医院就诊。


被猫狗等咬首先即刻对伤口进行清洗消毒，可用肥皂反复洗几次，并用水冲洗干净，再用碘酒进行消毒，然后在24小时内到防疫部门注射狂犬疫苗。注意：严禁招猫逗狗，接近危险动物！（这里找了一篇关于怎样在野外与狗狗斗争的帖子，长途骑行尤其人少的时候很有帮助···有兴趣可以看一下···）http://bbs.biketo.com/thread-424922-1-2.html

蛇咬伤 蛇比较令人害怕，没事自己千万别去山坡草丛里乱跑。不过除眼睛蛇外，蛇一般不会主动攻击人。我们没有发现它而过分逼近蛇体，或无意踩到蛇体时，它才咬人。遇到蛇如果它不向你主动进攻，千万不要惊扰它，尤其不要振动地面，最好等它逃遁，或者等人来救援.。若被蛇追逐时，应向山坡跑，或忽左忽右地转弯跑，切勿直跑或直向下坡跑。蛇怕风油精~

若被咬伤，可以先判断一下，无毒蛇咬伤常见四排细小的牙痕，毒蛇咬伤通常见一个或两个或三个比较大而深的牙痕，有的毒蛇有两排毒牙。无毒蛇咬后无须特殊处理，只需对伤口清洗、止血，去医院注射破伤风针即可。如果毒牙断在了肉里，要把它拔出来。一般步骤是先在2至5分钟内迅速在伤口靠近心脏上端5-10厘米处作环形结扎，不要太紧也不要太松。此后每隔20分钟放松1-2分钟，以免肢体因血液循环受阻而坏死。然后对伤口进行彻底清创处理，立即用双氧水或0.1%高锰酸钾，盐水或冷开水，肥皂水冲洗伤口，蛇毒在1至3分钟内不会蔓延。最好将伤肢置于４～７℃冰水中（冷水内放入冰块），在伤处周围放置碎冰维持２４小时，亦可喷氯乙烷（降温时注意全身保暖）。但一定切记不要在伤口处涂酒精。同时服用蛇药片！比如南通蛇药（季德蛇药）、上海蛇药、新鲜半边莲（蛇疔草）。在3－4小时后，或者注射抗毒血清后才能解除绑带。结扎后如果没有条件，最简单的方法是在保证腔粘膜和唇部无溃破的前提下用嘴吮吸，每吸一次要用清水漱口。

* 雷雨天气

最好穿胶鞋，披雨衣，可起到对电的绝缘作用。 尽量不要开门开窗。对突来雷电，应立即下蹲降低自己高度，同时将双脚并拢，以减少跨步电压带来的危害。 闪电打雷时，不要接近一切电力设施，如高压电线变压电器等。

* 皮肤过敏
内因：你本身是过敏体质。（肤色白、皮肤干、薄的人易过敏······）外因：饮食、吸入物、气候、接触过敏物因素。

1.保持皮肤清洁。春夏天多风沙，这些灰尘与分泌旺盛的皮脂相混合，易造成皮肤粗糙，故应时刻保持皮肤清洁，可用温和的洗面奶及柔肤水，帮助杀菌、清洁、柔软肌肤。

2.随时注意皮肤的保湿，增强皮肤的抵抗力，可选用清爽型、亲水性护肤品，原来冬季使用的含油多的护肤品应尽量少用。

3.注意风沙对皮肤的影响，平时皮肤较敏感的人尤其要注意用头巾遮挡，避免风吹。

4.饮食上多吃新鲜水果、蔬菜，少食刺激性强、易引起过敏反应的食物如海鲜、笋类等。

* 水中毒

这个名词或许比较陌生，但夏天发生的几率很大。主要是由于摄取水分过多导致脱水低钠症的中毒症状。轻度会疲劳，头痛呕吐；重度会引起性格变化，痉挛，昏睡，甚至呼吸困难。
主要还是要做好预防。

1 大量出汗以后，可以先用水漱漱口，润湿口腔和咽喉，然后喝少量水，停一会儿后再喝一些。每次以100毫升至150毫升为宜，间隔时间为半个小时。严格控制水分的摄取量，促进水分排泄，轻症患者在暂停给水后即可自行恢复，重度者及时送医院。

2 要及时补充盐分。适当地喝一些淡盐水，以补充人体大量排出的汗液带走的无机盐。在500毫升饮用水里加上1克盐，适时饮用。在补充机体需要的同时防止电解质紊乱。

3 要避免喝“冰”水。夏季气温高，人的体温也较高，喝下大量冷饮容易引起消化系统疾病，最好不要喝5℃以下的饮品。根据专家的建议，喝10℃左右的淡盐水比较科学。这样既可降温解渴，又不伤及肠胃，还能及时补充人体需要的盐分。

4 早餐一定要有液态食物，不论是牛奶、豆浆、果汁或稀饭，都能令机体充分地吸收水分和营养。

* 急腹症

即急性腹内脏器疾患所致的急腹痛。有两个特点：1．由于腹内脏器都有比较固定的位置， 腹痛部位与脏器病变部位较为一致。 如上腹中部疼痛多为胃、十二指肠溃疡穿孔，在下腹疼痛多为急性阑尾炎等。2．疼痛的性质与病因有着密切的关系， 如急性炎症引起的疼痛通常是持续性， 起病较缓慢，往往要经过几小时甚至一二天腹痛才比较剧烈。开始为压痛，甚至出现反跳痛和腹肌紧张(用手压上去时疼痛为压痛；用手指压上去后，当手指松开时疼痛较被按压时更甚，且出现突然的弹跳痛，这称为反跳痛；腹壁肌肉发生持续性收缩，按上去有发硬的感觉称为腹肌紧张)。又如，胃肠穿孔引起的急腹痛病，疼痛剧烈而持久，刀割性质，可迅速蔓延到其他部位，全腹可有压痛、反跳痛和腹肌紧张。由于引起急腹痛的原因很多，疾病的发展过程各有不同。所以当出现以上情况时，应尽快就医，进一步检查和处理。

在送医院之前，可以作一些早期处理：1．解松衣服，让病者安静地躺在安静的室内休息。 2．让病者自己选择舒适的体位休息。 3．出现呕吐时，可将冰袋放置在胃部， 但不要强制止呕。 4．不要马上给予食物，饮服药剂，特别是不要乱服乱用止痛药。5．应注意有无高热，并了解呼吸、脉搏和血压的情况，以便进一步处理。

* 烧烫伤

明火热水是危险事物，出门在外一定要格外小心，不要触碰。一旦发生严重情况，可按以下方法紧急处理：首先扑灭伤员身上明火。脱下鞋袜、手表、戒指、手镯等对烧伤部位具有束缚性的东西并立即在浸过开水或浓油的衣服上浇冷水，然后一边浇水一边脱衣，脱下困难时用剪刀将衣服剪开。但不要将贴在伤口上的任何衣服(包括被烧焦的)强行剥除。第二步用大量清水冲洗10-15分钟，化学灼伤冲洗20分钟以上。（生石灰例外）如果受伤面积较小，应立即以自来水冲洗或浸入冷水中，冷敷到感觉不出疼痛或灼热感为止。一般冷敷10—15分钟。然后进行包扎，以干净敷布将整个伤区轻轻包扎，敷布的末端可用夹子夹住。如有液体从敷布下渗出，再加一层敷布。数根手指、脚趾烧伤时一定要一根一根包上纱布。可将受伤肢体套在干净的塑料袋中加以保护。尽可能不要抓破水疱。水疱破后不要涂任何东西，马上送医院接受医生处理。

还有化学药品（强酸、强碱）灼伤：强酸灼伤要用大量清水处理，局部用2%-5%的碳酸氢钠或1%氨水或肥皂水中和酸，之后再用清水冲洗。眼睛要用大量清水冲洗，务必使伤眼向下。强碱灼伤先用大量清水冲洗，再用1%的醋酸中和剩余碱。无论怎样都切忌在冲洗前应用中和剂，防止大量产热，加重灼伤。

* 小贴士
** 紧急救护
** 止血位置和方法
指压止血法  适用于头面部或四肢动脉出血的临时止血。是根据动脉的分布情况，在出血动脉的近心端，用手指、手掌或拳头用力将该动脉压向深部的骨骼上，以阻断血流，达到止血目的。

头部指压止血点：

颞浅动脉

面动脉  颈总动脉

头顶部出血：同侧耳屏前方、颧弓根部的波动点即颞浅动脉，将动脉压向颞骨。手法：大拇指压迫，四肢并拢拖住下巴。颜面部出血：压迫同侧下颌骨下缘、咬肌前缘的搏动点，即面动脉，将动脉压向下颌骨。头后部出血：压迫同侧耳后乳突下稍后方的搏动点，即枕动脉，将动脉压向乳突。头颈部出血：压迫颈总动脉，同侧气管外侧、与胸锁乳突肌前缘中点之间的强搏动点，压向第五颈椎横突处。但两侧颈总动脉不可以同时压迫。（头部损伤应尽可能避免，骑车记得带头盔保护！）

前臂出血：压迫肱动脉，肱二头肌内侧沟中部的搏动点，将动脉压向肱骨干。手部出血：压迫尺、桡动脉：手腕横纹稍上处的内外侧搏动点，将动脉分别压向尺骨和桡骨。若手指出血，用拇指和食指压迫手指两侧血管即可，然后及时进行伤口清理，贴创可贴。

大腿出血：压迫股动脉，腹股沟中点稍下部的强搏动点，用拳头或双手拇指交叠用力压向耻骨。小腿出血：压迫腘窝中部的腘动脉。足部出血：压迫胫前动脉和胫后动脉，足背中部近脚腕处的搏动点，足跟内侧与内踝之间的搏动点。

*** 加压包扎止血
 是用毛巾、衣物、绷带等做软垫，放在伤口上，再加压包扎，以增加压力达到止血目的。

*** 直接法
检查伤口若无异物，将无菌纱布覆盖在伤口上，大小要超过伤口面积，直接用绷带或三角巾加压包扎。若第一块纱布被血液浸湿，可在其上继续加盖纱布。但不可取下湿透的纱布。

*** 间接法   如伤口上有刀、玻璃等不能移除的异物时，可保留异物，用敷料等固定异物，并在伤口四周施加压力，包扎止血。


*** 勒紧止血法
在伤口上端，用绷带、布带或三角巾叠成带状，先绕肢体一周为衬垫，第二圈压在第一圈上面勒紧打结。

*** 橡胶止血带止血法
抬高伤肢，在上止血带的部位以布巾或纱布衬垫，然后将橡胶止血带适当拉紧拉长，绕肢体2－3圈，最后将止血带末端压在紧缠的止血带下即可。但伤肢远端明显缺血或有严重挤压伤时禁用止血带止血法。

    止血带使用注意事项：上止血带前，应将伤肢抬高，促使静脉回流。位置选择上，在保证有效止血的前提下，尽量靠近出血部位，上肢结扎于上臂上1/3处，上臂中段禁止使用止血带，防止该处走行的桡神经受损。下肢结扎于大腿中下1/3处。止血带不能直接绑在肢体上，应垫衬垫。止血带松紧应适宜，以能止血为度。标准是，远端动脉性出血停止，动脉搏动消失，肢端变白。止血带应注明时间。每小时放松2min，松带要缓慢，并指压伤口。


*** 强屈关节止血法
无骨折的四肢出血，可在腋窝、肘窝、腘窝或腹股沟处，加上棉垫卷或绷带卷，然后尽力屈曲关节，用绷带或三角巾缚紧固定，借助衬垫物压迫动脉，阻断关节远端的血流而达到止血目的。

** 包扎
** 心肺复苏术
（胸外按压 口对口人工呼吸）

* 其他
1.长途骑行，不推荐携带背包和饮袋。不管重量是多少，只要有重量压在肩膀上，时间长了就会导致严

重的肩膀劳累，甚至肩膀压损。所以长途骑行宁愿用放在车架上的上管包，也不要背个包包在背后。
      2.长距离骑行之后，遇到非常陡的爬坡尽量保持要以低齿比（小档）慢慢磨上去，千万不能站起来摇车

，这样会导致大腿乳酸堆积迅速增加，很可能摇完车后就会让大腿或者膝盖严重受损。
      3.崎岖地形经常使螺丝松动，要定期检查，上紧螺丝。注意车子发出的声音，如有异常要立即检查，找

出声音的出处。
      4.带上防晒霜。防潮垫、樟脑丸。
      5.骑车时，嘴里含些话梅，陈皮等小食品可以缓解旅途的疲劳。
      6.一顶有檐的帽子---遮阳 挡雨 万一碰到夜间赶路，避免对面的汽车车灯恍眼看不清路面的危险。
      7.长途骑行后两脚会充血肿胀。休息时要平躺，尽可能把脚垫高，以促使血液循环。如有坡度不大的斜

坡，也可头朝下地躺下休息片刻或把脚放在自行车上休息一下。
      8.保管好自己的财物、照相机等贵重物品。
      9.尽量使坐垫和车把高度一致，利于背部肌肉放松。
