#+TITLE: casdu-editor
#+CREATED:       [2020-10-30 Fri 11:51]
#+LAST_MODIFIED: [2020-10-30 Fri 11:54]

It's personal choice to pick up whatever editor is.

But, I find [[https://emacs.org/][Emacs]] is great, and I want to share this to everyone who want to know.


People with VIM, atom, VScode, Notepad++, ... can also share their opinion.


* Why
[[https://emacs.lujianmei.com/beginners][by Lu Jianmei]]
> 在我接触Emacs后，从github、google上我发现了很多使用Emacs的人，有程序员，有记者，有科研人员，更多的一些经常发表文章的学者，他们来至于各行各业，做着不同的工作，但也有不少人虽然不是一个程序员，但因为使用Emacs久了，自然学会了如何简单的使用Elisp语言来配置一些简单的让自己的写作效率更高的东西，从他们的经历中，我可以很清楚的感受到他们的乐此不疲，可以感受到他们在Hack Emacs中获得的快乐，就像一个学习武术的人，已经开始在不断的与自己的宝剑，磨合到人剑合一的感觉，并发挥出更强大的力量； 所以我觉得只要一个经常打字的人，不管你是记者，还是一个作家，不管你是一个学生，还是一个科研人员，如果有兴趣学习Emacs，你就一定能在其中找到属于自己的一份快乐；Emacs有理由让你的付出一定会得到丰富的收获； 对于我来说，Emacs改变的不仅是我的写作习惯，而真正重要的，我觉得它改变的是我的整个学习和工作的方式，让我开始变的有序的组织自己的工作、生活、并在其中开始学习积累和记录工作、生活、学习所经历的东西，这也是激发我开始将我的学习内容和大家分享的最原始的动力； 我希望在带领大家学习和使用Emacs的路上，能带来一种轻松、快乐、有趣的经历，也能激发每一个读者领悟到与人分享中的快乐.
* Emacs on Windows
** why
- 这样的用户用emacs是为了什么 - TomoeMami
- 为什么emacs是最好的选择 by zhouchongzxc
- emacs的价值与意义 by Kinney
- 如果只是为了写issue的话，emacs未必是好的选择 by ianian
- `M-x help-with-tutorial-spec-language` 我是真心觉得 tutorial 好 by zmonster
- Mike Zamansky: https://www.youtube.com/channel/UCxkMDXQ5qzYOgXPRnOBrp1w by oracleyue

很长时间录制的一个名为Using Emacs的playlist，记录了他一点点学习Emacs以及各种mode的经历，简洁易懂，很平易近人，因为他是名老师，所以讲解和取舍都特别适合新手。国内应该也能找到他的视频。

** why emacs?
https://shreyas.ragavan.co/post/11ef85e6-9efc-4af4-b5f3-7648f9ee9308/
*** discussion https://emacs-china.org/t/emacs/13088/12

** how to learn
*** brief intro: http://steve-yegge.blogspot.com/2008/01/emergency-elisp.html?m=1

why: https://github.com/casdu/huikan/commit/7089f8424c5511c3f2a16c33febc2feb37eb2ecd

suggestions from experts: https://emacs-china.org/t/emacs/11902/11

https://evanmeek.github.io/2019/12/21/%E3%80%8AGNU-Emacs-Lisp%E7%BC%96%E7%A8%8B%E5%85%A5%E9%97%A8%E3%80%8B%E8%AF%BB%E4%B9%A6%E7%AC%94%E8%AE%B0/

** why org
https://lepisma.xyz/2016/03/17/org-mode/index.html

** log

*** <2020-02-21 Fri>
Step 0: 下载 Emacs 到电脑 并能打开 Emacs

https://www.gnu.org/software/emacs/download.html#windows

也可以参考这个帖子：

https://emacs-china.org/t/emacs/11902


Step 1 下载 26.3 并阅读Emacs Tutorial（完成）

 > Can you comfortable editing this file in Emacs? If not, please let me know.

Step 2 是不是下载jieba库，然后在上面进行编辑？

 > Please wait. There's huge gap there.

还没找到怎么把纯文字文档加载进Emacs上方法。

 > Can you open this file (README.org) in Emacs?


*** <2020-02-21 Fri>

 > 有点生疏，所以一些指令和语句我是放在一个文档中，边看边写。
It's okay. I did that when I first learn Emacs as well.

Check this: https://www.gnu.org/software/emacs/refcards/pdf/refcard.pdf

might be help.


> 没有自己写代码能力，但是至少可以根据别人的代码进行修改。

I am not as well. The power of Emacs is this. We just copy code from other people to do what we want.

What I've observed/experienced is that Elisp code is really easy to use.

> 比如根据一个已有的python 爬虫代码，爬取网页上片段文字（一门课程作业），费时较长。

That's whole another story.

I never did the "python 爬虫代码". But I collect some people who did that:

You can check: https://github.com/randomwangran/computing/blob/master/db/readme.org

The section: how you be a spider man

is useful, I copy from a very popular data scitentists's blog. You can study it. Share you experience, I can help.


> 下载 org文件至bin文件夹，C-x C-f 打开。

Good job. What did you see? Is it easy to use in Emacs with org-mode?
* questions
** QUELPA ／MELPA ／ ELAP 的关系／区别：(by twlz0ne)
https://emacs-china.org/t/outshine/12047/9
- ELPA 是 Emacs 包的发布规范。对比 Linux 的 deb, rpm。
- MELPA 是一个 Emacs 包的托管平台，开发者通过提交 recipe 到该项目来发布包，MELPA 审核完之后，开始拉取代码 -> 编译 -> 打包 -> 发布。
- QUELPA 直接把 MELPA 那一套代码搬（搬运工的搬）到本地。也就是说，你自己写一段 recipe 就可以了，不必提交给 MELAP 审核，QUELPA 会按 MELPA 的步骤拉取代码 -> 编译，但是不打包，而是直接“发布”到 ~/.emacs.d/elpa。
