:PROPERTIES:
:ID:       c9af88f2-8bc6-4196-9271-89f8baa7ee73
:LAST_MODIFIED: [2021-08-07 Sat 13:57]
:END:
#+TITLE: casdu-screw
#+CREATED:       [2020-10-30 Fri 12:09]
#+LAST_MODIFIED: [2021-08-07 Sat 13:57]
#+filetags: casdu

* 功能
1. 连接或固定物体：例如锁紧把手，龙头，座杆
2. 调整距离      ：调整变速器的L/H限制螺丝
* 螺丝的分类
** 方向
*** 右螺纹 (顺牙/正牙/顺时针)
*** 左螺纹 (逆牙/反牙/逆时针)
目前自行车上的逆牙，只有五通BB和踏板，这两个地方会用到反牙。其它的都是正牙。
*** 判断方式
以下是在在车店很常见的情形：去别的地方调货，拿到一个无盒裸装的英国牙BB，看不懂英文数字规格时，有一个最简单的将螺牙那一面正对着自己，如果螺牙方向为右旋上，则是正牙。如果是左旋上，则为反牙。
** 外径大小
Def: `以牙顶为圆周外径，所测量出来的直径大小.`

以牙顶为外径（注意！不是以螺丝头为外径！），去测量螺丝的直径，如果直径是5mm，那就是称做M5螺丝，如果直径6mm，则是M6螺丝。另外，M5这和我们常说的＜5号＞不太一样，一般讲的5号，正确来说是指六角扳手的尺寸，并非是指螺丝的尺寸，这点要特别注意。


但实际上，你拿标尺量出来的结果，数字会再小一点，例如M5实际测量的答案会
在4.9mm。下图则是M5螺丝外径实际测量的结果，可以看到光标卡尺数字显示为
4.91mm，并非刚好5mm整。
** 螺距
Def: `牙顶与牙顶的间隙距离`

这也是螺丝的重要单位。如果是公制单位的螺丝，它的每个牙尖的距离，是以公
制单位为基准. 以常见的龙头螺丝为例，有的会用M5*0.8来表示，M代表公制，5
代表螺纹外径为5mm，0.8代表每个牙顶之间的距离为0.8mm。

英国牙(English Threads)的计算方式，就是指在1英吋长度里，有几个牙顶。
以英国牙BB为例，可以在BB外壳上看到英文数字写1.37 inch x 24 tpi，那个
1.37代表的是螺牙的外径为1.37英吋，24tpi代表在1英吋长度里有24个牙顶。　

意大利牙则是一种混用公制单位和英制单位的牙纹。意大利牙BB，数字上会写着
36mm x 24 tpi，代表螺牙直径为36mm，24tpi代表在1英吋长度里有24个牙峰。

下面这张图是M5*0.8的螺丝，可以看到螺丝牙的长度量出来是13.68mm，然后
中间相隔17个牙顶间距，13.68mm除以17=0.80mm，所以螺距为0.8mm。

英国牙在台湾常被叫成日本牙，来源已不可考，但在英文中并没有这种称呼，所
以还是请大家讲正确的用语：英国牙。意大利牙它是混用公制和英制单位。　　

** 材质
在单车上，常见有的钢，铝合金，钛合金这种三种质，目前也开始有自行车厂商
采用碳纤维螺丝。
*** 铝螺丝
常见的问题：无法承受大量侧向力量，会容易断掉。
*** 钛螺丝
常见的问题：螺丝都快摧到爆了，但被锁物体仍会滑动，而且还会有bia bia的
声音。
*** 钢螺丝
**** 不锈钢
**** 合金钢（会生锈)
合金钢螺丝又比不锈钢螺丝能锁得紧。跟铝螺和钛螺丝相比，钢类螺丝比较能锁
得紧物体

** 螺丝头
*** 内六角螺丝
*** 十字螺丝
*** 一字螺丝
*** 套筒螺丝
*** 六角梅花螺丝

** Attached2
*** 中轴
*** 花鼓
*** 飞轮
*** 中锁碟片
*** 脚踏
I was laungh by Monkey that I still did not know how to unscrew a
pedal by one shot. So, that's the motivation for this rep.
**** uninstall
***** chain-side
https://youtu.be/YmPkYMPVqQU?t=103

 #+begin_src
                                           $"   *.      *Bike*
               d$$$$$$$P"                  $    J
                   ^$.                     4r  "
                   d"b                    .db
                  P   $                  e" $
         ..ec.. ."     *.              zP   $.zec..
     .^        3*b.     *.           .P" .@"4F      "4
   ."         d"  ^b.    *c        .$"  d"   $         %
  /          P      $.    "c      d"   @     3r         3
 4        .eE........$r===e$$$$eeP    J       *..        b
 $       $$$$$       $   4$$$$$$$     F       d$$$.      4
 $       $$$$$       $   4$$$$$$$     L       *$$$"      4
 4         "      ""3P ===$$$$$$"     3                  P
  *                 $       """        b                J
   ".             .P                    %.             @
     %.         z*"    .                 ^%.        .r"
        "*==*""        .                    ^"*==*""   Gilo94'
                       .
                     .....   Press Down the level
                      ...
                       .
 #+end_src

***** non-drive side
https://youtu.be/YmPkYMPVqQU?t=76
 #+begin_src
                                           $"   *.      *Bike*
               d$$$$$$$P"                  $    J
                   ^$.                     4r  "
                   d"b                    .db
                  P   $                  e" $
         ..ec.. ."     *.              zP   $.zec..
     .^        3*b.     *.           .P" .@"4F      "4
   ."         d"  ^b.    *c        .$"  d"   $         %
  /          P      $.    "c      d"   @     3r         3
 4        .eE........$r===e$$$$eeP    J       *..        b
 $       $$$$$       $   4$$$$$$$     F       d$$$.      4
 $       $$$$$             $$$$$      L       *$$$"      4
 4        ----o              /        3                  P
  *                         /          b                J
   ".                      /            %.             @
     %.        \          /              ^%.        .r"
        "*      \        /                  ^"*==*""   Gilo94'
                 \      /
                  \    /
                  _\/ /


               Push Forward
 #+end_src

** 必须上紧的螺丝
*** 把横的四颗或者两颗螺丝（4/5mm内六角）
*** 把立的两颗螺丝（5mm内六角）
*** 刹把和指拨位置的两颗或一颗螺丝（夹环上的螺丝）（4/5mm内六角）
*** 可锁死把套的一颗或者两颗螺丝（2.5/3mm内六角）
*** 一体式指拨防水盖／分体式指拨的防水螺丝一颗或者两颗（小号十字螺丝刀）
*** 刹车夹器的两颗螺丝（5mm内六角）
*** 来令片的一颗长螺丝（2.5mm内六角）
*** 刹车夹器转接座的两颗螺丝（5mm内六角）
*** 六钉碟片的六颗螺丝（T25六角梅花）
*** V刹刹车块的螺丝（其实是螺母）（5mm内六角）
*** 坐垫的一颗或者两颗螺丝（5/6mm内六角／活口扳手）
*** 锁死坐管夹的一颗或者两颗螺丝（4mm内六角／T25/30六角梅花）
*** 水壶架的两颗螺丝（4mm内六角）
*** 前拨的一颗或者两颗螺丝（5mm内六角）
*** 前拨线的一颗螺丝（5mm内六角／9mm套筒）
*** 一体式中轴左侧曲柄的两颗螺丝（5mm内六角）
*** 方孔／花键中轴曲柄，且具有防水作用的防水螺丝左右各一（8mm内六角或者套筒**）
*** 盘片的四颗螺丝（5mm内六角／T30六角梅花）
*** 普通后货架的螺丝共六颗（4mm内六角）
*** U型片的螺丝一颗（M3十字螺丝刀）
*** 脚撑（支撑）的两颗或者四颗或者更多螺丝（T25六角梅花／4/5/6mm内六角）
*** 尾钩的两颗或者一颗螺丝（2.5mm内六角（MERIDA，两颗）／5mm内六角（GIANT，一颗））
*** 后拨的螺丝一颗（5mm内六角）
*** 导向轮／张力轮的螺丝各一颗（3mm内六角）
* 工具：
** 不同型号的内六角（2/2.5/3/4/5/6/8/10mm）
** 十字螺丝刀
** 一字螺丝刀
** 六角梅花螺丝刀（T25/27/30)
** 套筒（8/9/10mm)
** 活口扳手
** 薄片扳手（14/15/16/17）
* 其他螺丝
压紧前叉的碗组盖螺丝：以前轮能够自由转向为前提下，最紧。（4/5mm内六角）
前后拨限位螺丝：合适位置（十字螺丝刀）
后拨张力螺丝：合适位置（十字螺丝刀）
前后拨微调螺丝：合适位置
V刹张力螺丝：合适位置（十字螺丝刀）
* 其他螺纹架构
前后轮快拆：上紧
脚踏：上紧（15mm扳手／6/8mm内六角）
中央锁死碟片、飞轮：上紧（专用／通用套筒***）
快拆式坐管夹：保证坐管不会上下左右移动
前叉气室盖：拧紧
滚珠花鼓两侧固定螺母：保证两侧等距，使轮子不会晃动（15/16/17mm薄片扳手）
培林花鼓两侧固定螺纹：5mm内六角上紧。
美嘴内胎气门：上紧（气门扳手）
法嘴内胎固定环：上紧
一体式中轴左侧固定螺丝：上紧（专用工具为八齿）
一体式中轴外挂部分（BB）：上紧（专用工具：两种规格）
方孔／花键中轴：上紧（专用套筒）
快拆式后货架：上紧

注：油压碟刹、前叉作为整体结构，螺丝不予讨论。
注：*代表“并不是所有车上都存在”的结构。

- 有两种螺丝，一种是内六角的一种是套筒的（套筒的不常见）

- 卡飞和旋飞的套筒本来应该是分开的，但是现在主要用的都是通用的套筒。这
  两种飞轮套筒都可以拆装Shimano家的中锁碟片。
* todo
- add 照片
- using https://github.com/the-humanities/org-mind-map to make a
  structure of the screw
