#+TITLE: casdu-why-we-bike
#+CREATED:       [2020-10-30 Fri 11:57]
#+LAST_MODIFIED: [2020-10-30 Fri 11:57]

* 十周年聚会

[104:05  (2005年会长): 我们是为了寻找简单的这份快乐而来,这是车协的初衷.](https://www.bilibili.com/video/BV13t411U7HB?p=11)

* [[远征]]
** 远征，我们到底“征”了些什么呢?

> 现在回头看看，最让我念念不忘的其实是上路前的那些经历。那种为了它去挣扎的拼劲，几个人相约着半年刷了近百次怪坡，不知道现在还有这场景吗，远征评审时有句话，现在还记得很清楚：你们药乡冲线那一刻的表情，决定了我是否为你们去辩护。

> 和很多人一样，这趟远征让我“征”服了慵懒的、内向的自己，至于远征时达到的成果，和上面说的一样，大致也仅限于了解沿途风土人情，以及社会实践用力去做的一段经历，真要说出能让自己吹逼一生亦或是可以放到自己投职简历上的成果，大致是没有的。



** Racing
*** why I like mountain bike

对我来说，与其说是喜欢山地，不如说是喜欢“山地”吧。现在生活的地方，方圆千里之内没有一座山，所以这种对比就特别明显。大学四年，雷达八角南部山区，每次进山的时候都能发现一些从来没走过的路，然后下一次的探险，就会把心中的地图，扩展得越来越大。这种探险的乐趣，也只有山地车才能帮我做到。

山地车的另外一种乐趣，是挑战林道越野的刺激。这种林道不是雷达站也不是京赛的那种，而是藏匿于雷达站/京赛训练赛道的，鲜有人知晓的羊肠小道。那种，你自己很清楚，哪怕稍微地一丁点地分神，比如没能注意到前进路线上的起伏碎石/前方树木枝桠的空间位置/食指点刹车的力度/用前刹或是后刹的选择/身体重心的相对位置...,就会造成严重摔车后果，所产生的高度精神集中的瞬间，是我超喜欢山地越野的一点。

这两点，是公路自行车上非常难体验到的乐趣。


*** why I like road bike

在公路车/山马上则体验到的是另外一些不同的乐趣。通过训练，不断地去突破生理上极限，身体内那些神奇的化学反应本身是一种乐趣；训练的时候，仔细地观察那种身体和肉体互相冲突的体验；在有对手/观众的时候，心率/功率数据和主观感受的巨大差异...让我也逐渐开始相信自行车训练的不是单是身体，更是精神。

很长一段时间里，我问自己，为什么骑车？我不是职业车手，这样[对着功率计](https://github.com/casdu/training)以近乎职业车手的要求来对待骑车有什么用？因为知道自己终究不会成为职业车手，所以练成什么样都无所谓。于是在很长的时间里，我只是把自行车训练当作是锻炼身体的一种方式。而锻炼的身体的方式多种多样，骑车并不是唯一，所以很容易就把注意力转移到了别的地方。结构化的训练也就无从谈起，也就直接体现在功率数据上的止步不前。而现在我的想法：只要我去训练，我就是职业车手！多年来的骑车经历，教会了我很多东西，比如，友情，勇气，旅行，拼搏，奉献...但是自行车给我最珍贵的东西，我觉得是它对我性格的塑造。简单来说就是变得精神上的强壮( hard-core 或者 mentally-strong )。无数次爬陡坡被榨干的体力，盛夏骄阳似火的灼烧，六九寒冬的冰晶，跋涉千里的远行...而结构化的训练，也正是在这本书中提到的刻意练习，则更是对这种性格的提升。我想通过这种训练，告诉自己，也告诉全世界，我是一个怎样的人。而这一点，即便是在终将有一天我不能再骑车的日子里，也不会后悔的东西。训练改变的不仅是身体，它改变的更是我的精神。
