#+TITLE: Feb 23rd, 2021

** [[file:../pages/ftp.org][FTP]]

What's a better solution?

[quote="OreoCookie, post:12, topic:53833"]
The goal is kinda weird and conflicts with the goals or TR’s training plans.
[/quote]

In my opinion, my goal is very clear. Try to raise the number during the last minute of the RAMP test.

I set this goal because I do not have any chance to race. Maybe one in a year or once in two years. This is not to say that I do not like race. I like to race but I do not have this privilege too often. Instead, I am seeking a tangible goal. 

[quote="OreoCookie, post:12, topic:53833"]
For example, the goal of the specialty phase is *not* to raise your FTP
[/quote]

This is the reason why I avoid specialty phase because I found that I do not have too much FTP progress after finishing this. 

[quote="OreoCookie, post:12, topic:53833"]
Short power build emphasizes shorter efforts.
[/quote]

This is the reason why I prefer short power because I think the RAMP test is more correlated to short maximum power.  

[quote="OreoCookie, post:12, topic:53833"]
What you are asking is to get good at one test
[/quote]

Exactly. I am not sure by setting a clear and defined goal would help to achieve this goal better or not.

[quote="OreoCookie, post:12, topic:53833"]
you might mentally burn out.
[/quote]

This is why I cannot consistently train at a relatively higher training session in the past. I am trying to add more endurance training with the hope to reduce the physical stress during the hard sessions.  As I said, I will look at it very closely and adjust my training accordingly.
** [quote="OreoCookie, post:14, topic:53833"]
Making an arbitrary number in a test is usually not such a great goal. I suggest you focus mostly on process goals.
[/quote]

I like your idea about process goals instead of "target" goals. Yes, 300 watts itself does not mean anything. It is no different from 299, 301, or even 290 (if an error bar considered). But I do think setting such a goal has value.

> “If a man knows not which port he sails, no wind is favorable.” – Seneca

Thanks for your suggestion on these [[actionable goals about cycling]]:

I will add them as my sub-goal during this journey.

Also, the suggestion on sleep is critical. I have a very bad sleeping state during the "demotivated" time period and this is something I should look for improvement.
