#+TITLE: Mar 2nd, 2021

** [[file:../pages/polarize training v.s. sweet spot training.org][polarize training v.s. sweet spot training]]
*** [quote="OreoCookie, post:24, topic:53833"]
I have the impression you want to benchmark TR’s Base + Build (- Specialty) approach to polarized training.
[/quote]

Yes. I would like to do it at least a full cycle this year and perhaps 2 to 3 times this year. Currently, I feel good.

[quote="OreoCookie, post:24, topic:53833"]
Base might, but Base is just one out of three phases. And one of the main benefits of polarized training is that it raises the tail end of your power curve — also that is not easily detectable with a ramp or 20-minute FTP test
[/quote]

I concur with you. Base lays the foundation of my fitness. I think that I might do too much time in the sweet spot zone. I think that the Short Power Build will add a decent time in the zone over the sweet spot. But I would like to say that I do not know that such a time and power distribution would benefit my goal this year, i.e. target at 400 MAP using TR ramp test.

[quote="OreoCookie, post:24, topic:53833"]
Personally, I’d just try to improve aspects of your training while maintaining a structured approach as if it were a season.
[/quote]

I am glad to see this. Would you like to share what you did this year? What was your goal last year? How is this year? What would you like to compare? I am sure there are many people who like to see such a long time experience at the personal level. I have a similar plan to see what works whatnot. It will take time to see the result, but I think it is fun.

[quote="OreoCookie, post:24, topic:53833"]
For example, if you want to try polarized training, you should find out what a 1-season polarized training plan *actually* looks like and follow that.
[/quote]

Exactly, I would like to do the baseline as a comparison group this year and I will probably do the POL next season to see how it goes.

I will definitely contact @Bbt67 sometime later this season. I would like to see if I can consistently execute TR plan first before consulting with the expert.
*** TODO [quote="Craig_G, post:26, topic:53833"]
:PROPERTIES:
:todo: 1614728416584
:END:
I think a confusing part for some people (myself included) is that the ramp test is used to estimate FTP. But it doesn’t sound like you care about FTP, you care about the last minute of the ramp test (i.e max aerobic power.)
[/quote]

I think that the care is less from my perspective. During the last 5 years, I only did two races, yet I still like training with TR. To some extend, I care about FTP as a relative tool to eval my fitness as a cyclist.

This is some kind of psychology trick for me.
