#+TITLE: Mar 10th, 2021

** [[bike fix]]
*** How to remove tires on the road more easily?
- limited tools
- 23, 25, 28, ... Are they interchangeable?
*** crankset movment
**** I used a 5 mm spacer on a SARM British BB over 2~3 years without knowing there is an issue. I thought BB was a bad product until I happen to find a video on do we need a spacer on my bike frame?
*** Tips
**** chain remove tool saves me a lot
***** I used  to remove the quick-release chain by bare hand on an elongate chain (too much pain)
**** use big seat-bag
**** shinano hand protection gloves save my hand
** [[Machine learning in cycling training]]
*** That's when I start to really look into ML.
** [[My training story]]
*** Just want to write
*** Today, I've done SSB High Volume 2 week 4 ((8a9da84f-447e-460b-b5c4-b21383d487ae))
**** Day 3, on the 4th set, I tried to follow an electric bike, which I push over 300 watts for 3~4 minutes. But I can only see the rider distancing me little by little. What an electric bike.
**** My derailleur is not accurate
- switch to big gear no big issue
- switch to small gear is the most headache one
- new chain and ((692d9d1c-b09d-481e-9aeb-eff64b4c2f53)) is incompatible, which I feel strange. They are new components, should have no issue? Does it mean that the chainring has some issue?
**** My bike fit still need to be improved
My hands and shoulders are not very comfortable even just a 2 hour SSB training session

 - handlebar reach is too long, I prefer 60mm. Right now it is like 100mm
- stem is too long, I prefer 60 mm. Right now it is like 90mm
- seatpost is offset 20mm, I want to have a zero-offset one
** [[Cycling news]]

((604989f9-c257-41e2-8311-d1c75b02198f)) issue stalls Cavagna's attack in Paris-Nice
