:PROPERTIES:
:ID:       3bc4cfd5-166c-4038-a2a3-150d8d433ee2
:LAST_MODIFIED: [2021-08-07 Sat 14:00]
:END:
#+TITLE: 2021-winter
#+filetags: casdu

** link
https://www.bilibili.com/video/BV1Nt4y1z72H
** 评论
相对于大山大河的西部，我印象中沿海东部的骑行不会有太多波澜的故事。但这个视频，虽故事只有短短七天，却把所有经历讲得非常鲜活。非常喜欢《山木诗词全集》里面简单节奏的背景音乐，搭配东游队员自己的声音，讲述镜头之外的故事，作为一个观众，感觉非常真实。很喜欢郝云的《活着》，作为队歌，把这段旅途的意义诠释了出来。
**** Day 1
“当时天还没有完全亮，我们是顶着夜色出发的。我跟在两个女生后面，看着她们的后货架还有驼包，那种感觉是特别新奇。” 经十路上的那段骑行视频，太有带入感。
**** Day 2
平淡的鲁南，小上坡。
**** Day 3
距离枣庄还有23公里的地方，“欢送[[前站]]”。

“东游里，印象最深的一天就是璟琨的生日。全队没有爆胎，这对于我来说是最好的生日礼物了。”

“我们经过一马平川的田野，经过了冬日萧索的苏北农村，远处有巨人般的风车，这比国道有趣多了。”

“感觉这是我最有意义的生日，因为这一天见过了很多人很多事，朝着家的方向前进。”

“但万事都一笑而过，生活还有什么意思呢？”
**** Day 4
“快乐是比较出来的。骑车太累了，肚子特别饿，停下来休息就很快乐。”
""
**** Day 5
“这就是南方吗？风景又好，饭又管饱。”

“它不是一场说走就走的旅行，而是有计划有预谋的，让你被周围的人感染，一点一点地喜欢上车协。”
** 视频相关
*** [[BGM]]
**** 《山木诗词全集》
**** 《活着》
*** 问题

> 咱B站粉丝一直涨粉速度很慢，但是比起我接手前粉丝数量已经多了一倍多了。

非常棒了！而且我注意到视频的作者，并没有直接参与到东游中，也能做出质量很棒的视频。

> 叙事性强的视频更能留住人，海南岛那个一开始人很多，看了一会发现比较单调就不看了。质量越高的视频前30s关掉界面的人越少，前30s如何抓睛是新的问题。

我特别喜欢这种类型的视频，特别是和自行车相关的旅行类 vlog。带入感特别强烈，一般视频中的节奏都不会很快，能让人静下心来去体验一些不太可能的一些经历。

> 考虑把前10s的片头撤了。下次尝试做镂空片头，场景和logo都能有。

Casdu Logo 加塔基的声音挺有特色的。作为一个协会的传承，我个人感觉不错。镂空片头可能技术上实现起来要难一些。能在前10秒中加入更多细节的同时又有一定程度的传承，肯定会更好。

> 以后可以尝试加入队医和技术员知识，且日常拉练急需航拍视角。

赞同。视频灵感的来源，大家都可以提出想法，交流自己的心得，我想素材就会越来越多。

感谢岳晟！视频真的是做得越来越好！
