:PROPERTIES:
:ID:
:LAST_MODIFIED: [2022-09-04 Sun 10:47]
:END:
#+title: jinan
#+created:       [2022-08-05 Fri 22:55]
#+last_modified: [2022-09-04 Sun 10:49]
#+startup: showall

* 济南 72 泉
  :PROPERTIES:
  :ID:       d091a8f6-c283-45b0-9a2a-5777ab2e4243
  :ROAM_ALIASES: "72 spring"
  :END:
  - [[http://bbs.casdu.cn/forum.php?mod=viewthread&tid=10225&extra=page%3D1][由康梦露编写]]
** 一 趵突泉
 　　趵突泉位于趵突泉公园内的泺源堂前。居“七十二名泉”之首，更有“天下第一泉”的美誉。北魏《水经注》称“泺水”；“趵突泉”名见于文字的最早记载是宋代熙宁六年(1072年)曾巩撰《齐州二堂记》。趵突泉泉水喷涌达26.49米，最大涌水量16．2万立方米／日。泉池长30米，宽18米，深2.2米。周围建有观澜亭、泺源堂、来鹤桥、蓬山旧迹坊及历代名人题咏趵突泉诗文碑刻等名胜古迹。1956年，依泉建园称趵突泉公园。
** 二 登州泉
 　　登州泉位于趵突泉公园内趵突泉西侧。传说因水脉通登州而得名。池长3米，宽2米，深4米。周围有深度、结构与之相同的环池。
** 三 东高泉
 　   位于趵突泉公园内万竹园东南侧，泉池方形，自然石砌成，长、宽4米，深1.5米，池东岸立清末已酉年（1909）石碑，上题楷书“东高泉”。曾列为金、明两代七十二名泉。
** 四 杜康泉
 　　杜康泉(原名北煮糠泉)位于趵突泉公园内，趵突泉的西北侧。传说因酒仙杜康曾于此地置锅煮酒而得名。水势旺盛，清冽甘美。泉池为块石砌垒，呈长方形，长2.4米，宽2米，四周饰以栏杆，池上建石亭，额悬“杜康泉”木匾。
** 五 皇华泉
 　　皇华泉位于趵突泉公园内柳絮泉西侧，皇华轩门前。皇华泉得名于《诗经·小雅》中的“皇皇者华”。泉池呈长方池，长6.3米，宽4.1米,深2米，周围绕以石雕栏杆。水自池底涌出，澄澈晶莹。池内北壁嵌着名书法家魏启后先生题写的“皇华泉”石刻。
** 六 金线泉
 　　金线泉位于趵突泉公园内趵突泉东北侧，尚志堂与皇华轩之间。金线泉池呈长方形，长2米，宽1米，深1.5米，泉水自池底两边涌出，且流势相当，在水面相交，聚成一条水纹，映日凝望，宛如一条金光闪闪的金线浮于水面，故而得名。
** 七 白云泉
     白云泉位于趵突泉公园内万竹园的西花园西南角，静卧在一片绿洲灌木丛中。这里泉溪相连，流水潺潺，假山堆岸，花木扶疏。泉池南端有一泻口，为自然石垒砌，呈多层叠状，水满流溢，可形成多层叠水。泉水沿着曲折的小溪蜿蜒东流，至万竹园门口与东高泉之水汇合，继续东流至趵突泉边的沟渠。
** 八 柳絮泉
 　　柳絮泉位于趵突泉公园内，与金线泉隔壁相连。池长3.5米，宽3.2米，深1.5米。因泉中气泡翻飞，银光闪闪，泉花串串，常年“泉沫纷繁，如絮飞舞”而得名。
** 九 马跑泉
 　　马跑泉位于趵突泉公园内李清照纪念堂东侧假山下。因抗金英雄关胜的战马怒啸奔腾，刨地出泉的传说而得名。泉池长12米，宽5米，呈不规则形，池岸由已溶蚀的石灰岩岩石砌垒，曲折起伏，参差交错。泉水从石隙中流出，沿池底小溪向东北流去，注入护城河（西泺河）中。泉池周围，怪石嶙峋，绿树掩映，显得格外幽雅别致。
** 十 满井泉
 　　满井泉位于趵突泉公园内的娥英祠西北隅。因四季涌泉，盈溢井口而得名。填埋多年，1997年修复，泉池呈六角形，深5米，石砌井壁，周饰雕石栏杆，栏板嵌“满井泉”名刻。
** 十一 石湾泉
 　　石湾泉位于趵突泉公园内，白雪楼前。因巨石驳岸，状如水湾而得名。原池淤塞已久，1977年修复，池长宽各10米，深1．5米，与湛露泉相连，以石砌垒，南依假山，池岸岩石上镌“石湾泉”名刻。
** 十二 漱玉泉
 　　漱玉泉位于趵突泉公园内，李清照纪念堂南侧。泉名由“漱石枕流”一词演化而来。相传宋代女词人李清照常于此填词吟诗，梳洗打扮。她的作品《漱玉集》即以此命题。泉池长4.8米，宽3.1米，深2米，以石砌垒，周饰雕石栏杆，北侧栏板嵌“漱玉泉”名刻。水自池底或池壁涌出，漫石穿溪，汇入长24米，不规则形石砌水塘。
** 十三 望水泉
 　　望水泉位于趵突泉公园万竹园西院。相传此泉与万竹园内的另一名泉--登州泉相通，齐望登州，故名“望水泉”。泉池长20米，宽9.8米，深2.2米，中架3孔石桥，桥南建石亭，游人可于亭桥观鱼赏景，池北有与院落相通的门楼。桥西侧北岸池壁嵌清末庚戊(1910年)“望水泉”石刻。
** 十四 卧牛泉
 卧牛泉位于趵突泉公园内，与皇华泉并列皇华轩门前。传说常有耕牛躺卧泉旁休息而得名。池长6.3米，宽4.1米，深2米，北岸石栏上嵌“卧牛泉”名刻。
** 十五 无忧泉
 　　无忧泉位于趵突泉公园内，东南临白雪楼，以酌饮此水能消愁解忧而得名。泉池呈不规则形，以自然石缀岸，水自西南部弯月形泉池中的岩孔涌出，喷珠溅玉，聚为面积672平方米的池塘，然后从北岸溢出，汇入趵突泉。
** 十六 湛露泉
 　　湛露泉位于趵突泉公园内白雪楼前，与石湾泉相邻，金《名泉碑》,明《七十二名泉诗》均收录。因泉水清湛，甘香味美而得名。泉池填埋多年，1997年修复，池长、宽各4米，深1.5米，西部以自然石驳岸，参差曲折，半浸水中的岩石上镌“湛露泉”名刻。
** 十七 黑虎泉
 　　黑虎泉位于济南市黑虎泉西路环城公园东南隅，北与解放阁隔河相对。因水声轰鸣，状若虎啸，或洞卧巨石，形似卧虎而得名。泉水标高27.88米，水自高2米、宽1.5米、深3米的洞穴岩孔涌出，从3个石雕龙头口中喷入长13米、宽9米的石砌方池，由池北岸泻入护城河，形成一道白色水帘，与周围，山石树木、楼台亭阁、曲径拱桥等园林建筑相互辉映，蔚为壮观。
** 十八 白石泉
 　　白石泉位于黑虎泉东侧河中。清道光《济南府志》载：“白石泉，乾隆甲寅江方伯因旱浚泉雨后涌出，曲阜桂馥有记。”因泉周有许多白石出没于水面而得名。池以自然石驳岸。长6米，宽5米。水由池岸石隙流出，汇入护城河。
** 十九 回马泉
 　　回马泉位于五龙潭公园内五龙潭南侧，东邻古温泉。相传唐朝武将秦琼五龙潭内建府邸，在此遛马，战马空腾，马蹄落地处出现泉眼，故取名为回马泉。泉池呈长方形，水面与“净池”相连，约50平方米，水深2米。池中间建一曲桥回廊，设有座栏，供游人凭栏观鱼赏泉。南岸池壁上有“回马泉”刻石。回马泉、净池的泉水汇流成一股溪流，由南向北由玉泉边上的一座小石桥下流过，注入五龙潭。
** 二十 九女泉
 　　九女泉位于解放阁南侧护城河北岸边，与玛瑙泉隔河相对。民国17年(1928年)《历城县乡土调查录》载：“在南关黑虎泉，北依城壕，现在安宅新建房内。”因临九女楼(一说因常有九天仙女于清风月夜来此浣纱沐浴的传说)而得名。泉池长8米，宽5米，深2米，自然石驳岸，半伸河中，水自岩孔涌出，形成涟漪荡漾的水湾，穿过池岸流入护城河内。
** 二十一 玛瑙泉
 　　玛瑙泉位于黑虎泉东侧河边。民国17年(1928年)《历城县乡土调查录》有记载：“在县城东南三皇庙下崖桥西南”。因水自池底涌起串串水泡，经阳光照射，五彩缤纷，犹如玛瑙而得名。池呈方形，长3.7米，宽3.2米，深2.7米，以块石砌岸。池水从池上部7个分孔流出，漂落护城河，状如垂帘
** 二十二 琵琶泉
 　　琵琶泉位于环城公园东南隅，黑虎泉西侧。因水声淙淙，犹如琵琶扬韵而得名。1965年整修为长6米、宽5米、深2米的石砌方池，水自池底岩孔涌出，由北岸溢出，跌宕下泻，迸落河中，立于琵琶桥上赏泉听音，别有风趣。
** 二十三 五莲泉
 　　五莲泉位于济南环城公园东南隅，琵琶泉西侧。池底泉眼甚多，较大者有五个，水泡成簇，于水面绽开，似五朵盛开的莲花，故名。泉南侧河岸上建有五莲轩，由亭、台、廊、榭组成，景观十分别致。
** 二十四 百脉泉
 　　百脉泉位于济南章丘市明水镇百脉泉公园内，为明水诸泉之冠。百脉泉水从许多看不见的脉孔中涌出，似百条大脉，泛出参差错落的颗颗“珍珠”。百脉泉池长26米，宽14.5米，深2米，池岸由青石砌垒，东西向架一虹桥，池岸和桥上装饰雕刻石栏。池底涌出数不清的水泡，缓缓地浮上水面，好象滚动的珍珠，所以当地人也称为“珍珠泉”。泉壁和梵王宫大殿墙上镶嵌着多方诗词、楹联、花卉石刻。其中有明代进士著名戏曲家李开先《游百脉泉》诗。
** 二十五 东麻湾
 　　东麻湾位于济南章丘市明水镇百脉泉公园内。清《济南府志》载：“东麻湾在百脉泉左百余步，泉源涌沸上出，西流汇于百脉泉”。因位于城东，湾内遍布密密麻麻的泉眼而得名。原为自然式塘湾洼地。1958年清挖扩建，面积达10余万平方米，称明水湖。1986年建百脉泉公园时，周砌石岸，净化水面，建岛架桥，增设游船，广植花木，成为公园独具特色的游览景区。
** 二十六 梅花泉
 　　梅花泉位于济南章丘市明水镇百脉泉公园清照园内，因布局成梅花形的5眼清泉而得名。泉池面积1500平方米，水自5个规格相同的铸管涌出，水花翻滚，微波四散，状如趵突，由泉池东岸过漫桥，汇东麻湾水入绣江河。
** 二十七 墨泉
 　　墨泉位于济南章丘市明水镇百脉泉公园内，龙泉寺门外。因泉水从铸铁管内涌出，黝深亮丽，(一说因原中共山东省委书记、著名书法家舒同同志任章丘县委书记时居住泉旁，常以此泉水研墨洗笔)而得名。泉池呈方形，雕石砌岸，饰石拦杆，涌水量0.3立方米/秒，水盛时达1立方米/秒，水自0.4米铸管喷涌，水花四散，自池北侧溢出沿石渠北流，汇梅花泉。
** 二十八 珍珠泉
 　　珍珠泉位于珍珠泉宾馆大院内。以平地涌泉，水泡升腾，如泻万斛珍珠而得名，又因城东南护城河中有南珍珠泉，故又名北珍珠泉。泉池呈方形，面积1240平方米，雕石砌岸，周饰石栏。
** 二十九 溪亭泉
 　　溪亭泉位于珍珠泉宾馆大院内，珍珠泉东侧。因附近溪流潺潺，亭阁翼然的园林景物而得名。泉池长2米，宽1.8米，深2米，以自然石砌岸，南、北、西三面绕以石雕护栏。东面为山石叠成的假山，古朴自然，石上镌王讷(字墨仙)题写的“溪亭泉”石刻。池南侧徐北文撰《溪亭泉题记》，文中有：李清照曾作《如梦令》有“尝记溪亭日暮，沉醉不知归路。兴尽晚归舟，误入藕花深处”之句，景物与此处相合。
** 三十 散水泉
 　　散水泉位于珍珠泉大院内，北临市级重点文物保护单位—清巡抚院署大堂。因泉水奋涌，涟漪旋回，聚而复散而得名。1981年重修泉池，长、宽各1.6米，深2米，石砌池岸，加建石栏。南岸栏板上镌“散水泉”，为省人大副主任李予昂书写。池内水清见底，晶莹碧透。
** 三十一 濋泉
 　　濋泉位于珍珠泉宾馆大院内，珍珠泉东30米处。泉池呈方形，长宽各1.45米，深2.5米，由块石砌垒。山东巡抚刘芳躅(字增美)人工挖掘而成，著名学者朱彝尊据《尔雅释水》中“济为濋”之意，起名为濋泉。1951年以石砌岸，周饰石栏，北壁和高石上嵌王讷(字墨仙)题写的“濋泉”石刻。
** 三十二 五龙潭
 　　五龙潭曾名灰湾泉，位于济南市中心五龙潭公园内，居公园中部。北魏郦道元《水经注》称净池，是大明湖的一部分。唐天宝四年，杜甫与李邕宴饮历下亭，即在古历亭遗址处。金代《名泉碑》收录，称灰湾泉。元代池旁建五龙庙，内塑五方神龙，后人便称其为五龙潭。历经整修，今池长70米，宽35米，以石砌岸，池广水深。溢水标高25.80米，日涌水量最高4.3万立方米。潭水沿石渠穿街过院，蜿蜒北流。1986年以潭建成五龙潭公园。
** 三十三 古温泉
 　　古温泉位于五龙潭公园内，五龙潭东南侧，北临省级重点文物保护单位——中共山东省领导机关旧址(1925年至1927年)。因泉水恒温18度左右，冬夏如一，古时称“温泉”而当地人又因历史久远，习惯上称“古温泉”。
** 三十四 官家池
 　　官家池，位于五龙潭公园内，五龙潭西北侧。《因附近居民共取此水为公众所有而得名。自然石驳岸，呈不规则形，池长6米，宽4米，深3米。水自池底多孔涌出，由东岸石上溢出。
** 三十五 濂泉
 濂泉地处五龙潭公园西北隅，泉池由自然石砌垒，北岸水边石上刻濂泉名，四周垂柳成荫。其泉池面积广阔，水质清澈。晨曦初升时，濂泉犹如一块凝璧；夕阳西下时，濂泉状似一盘金汤；迷雾烟雨中，它碧波荡漾；艳阳高照下，它熠熠生辉……浓妆淡抹总相宜的濂泉清逸凉爽，倒影成辉，聚柳树的婀娜多姿、清泉的温润碧透于一身，给人们清新明丽之感。濂泉池中立一小亭，名“寒玉亭”，亭接水廊，廊接“濂轩”，沿廊修竹郁森，巧石秀丽，临轩花木葱茏。
** 三十六 虬溪泉
 　　虬溪泉位于五龙潭公园内月牙泉东北侧。因泉水出露于状若虬龙的岩溪而得名。泉池由自然石垒砌，长、宽各7米，深1.4米，北岸岩石上镌“虬溪泉”名刻。水由泉池岩孔喷出，沿石溪穿竹林流入护城河。
** 三十七 天镜泉
 　　天镜泉位于五龙潭公园西南隅。因泉水平明，日月星云倒影如天垂镜而得名。明代刘敕纂《历乘》载：“天镜泉，昔名江家池，张元平(张鹤呜)观察改为天镜泉，其泉清澈可爱”。泉池长14.5米，宽13.6米，深1.4米，石砌池岸，最大日涌水量15500立方米。
** 三十八 西蜜脂泉
 　　西密脂泉位于济南市共青团路五龙潭公园西南侧，关帝庙院内。因水质甘美如蜜而得名。泉池雕石砌垒，中架石桥，分隔为两个对衬的方池，各池饰雕石栏杆，池水相通，总长5米，宽1.7米，深1.5米。
** 三十九 贤清泉
 　　贤清泉(又名悬清泉)位于五龙潭公园最北端。泉旁曾建伊人馆、贤清园、朗园等园林名胜。经1986年整修，浚池砌岸，池略呈方形，长22米，宽17米，深2米，临水植花木，架石桥，建回廊水榭，是游人品茗赏泉的好地方
** 四十 玉泉
 　玉泉位于五龙潭公园内五龙潭南侧。因泉水洁白如玉和原五龙庙中有一条白色雕龙的寓意取名。池岸以自然石砌垒，水自石中涌出，穿石隙，沿水渠蜿蜒东流月牙泉相汇后流入五龙潭。
** 四十一 月牙泉
 　　月牙泉位于五龙潭公园东南隅，古温泉东侧。民国17年(1928年)《续修历城县志》载：“在西门外东流水路东”。因形如初月而得名。泉池长13米，宽8米，深1.5米，以自然石驳岸，水中立有以纪念我国第一颗原子弹爆炸成功命名的蘑菇云石，水盛时可从3米高的石顶喷出，水花四溅，洒落泉池。池水沿曲溪，过石桥穿竹林，流入护城河。因月牙泉喷涌水位要求较高，所以月牙泉喷涌就标志着济南所有泉群全部喷涌。
** 四十二 袈裟泉
 　　袈裟泉(曾名独孤泉、印泉)，位于济南长清区万德镇灵岩寺风景区内。以泉旁有貌似袈裟的铸铁取名袈裟泉。泉水自岩洞石缝流出，汇入半圆形石砌池中，然后经曲溪由石雕龙头口中流入大型池塘。泉周危崖峻峭，丛木悬生，亭廊环绕，鸟语花香，别具风采。
** 四十三 甘露泉
     灵岩寺甘露泉位于灵济南长清区万德镇灵岩寺风景区内。是灵岩寺诸泉中最着名的一个，有“灵岩第一泉”之称。小泉似露珠般在石缝中泄出，叮咚作响，清冽甘美，故名“甘露泉”。泉池呈长方形，清澈见底，绿藻飘动，终年不涸。池东侧崖壁上嵌“甘露泉”石刻，为乾隆皇帝御笔。泉池西侧10余米岩壁上，嵌明嘉靖二十七年(1548年)山东巡抚彭黯所书“活水源头”巨字刻石。
** 四十四 卓锡泉
 　　卓锡泉位于济南长清区万德镇灵岩寺风景区的千佛殿东侧岩壁下，此处泉水竞流，古柏参天，题刻众多，是著名的灵岩八景之一。 传说因高僧用锡杖戳地出泉而得名。水自岩壁下部洞穴涌出，沿石渠漫流，与白鹤、双鹤等泉水汇入镜池，泉旁岩石上镌乾隆御书卓锡泉及咏泉诗一首。
** 四十五 檀抱泉
 　　檀抱泉位于济南长清区明孔山下第四峪村。因以石修建的洞穴式泉池上部有1株胸围1米左右的古青檀树取名。洞深、宽各3米，高1.2米，水自岩洞流出，积于1.8米石砌方池，再沿暗渠流入长40米，宽14米至20米的蓄水池。
** 四十六 晓露泉
 　　晓露泉位于济南张夏镇积家峪村北首石洞中。洞深4米，宽、高各2米。水自洞内岩孔涌出，流进井形池中，再由暗渠伏流洞外石砌方池。水盛时溢出池外，沿山沟，穿过农田、果园，蜿蜒向北，流入石店水库。
** 四十七 苦苣泉
   :PROPERTIES:
   :LAST_MODIFIED: [2022-09-04 Sun 10:49]
   :END:
 　　苦苣泉又名莴苣泉，位于柳埠镇袁洪峪度假村。泉池呈井形，内径0.5米，深4米，用玻璃板覆盖，水潜流罗曼山庄院内出露地面，由高2米，宽3米的山石跌落浅池。泉旁岩壁上镌苦苣泉碑记多方。

kǔ jù
** 四十八 避暑泉
 　　避暑泉位于济南南部山区柳埠镇袁洪峪度假村，泉因气候凉爽，宜于盛夏避暑而得名。泉池为半露崖处的封闭式圆池，水由池壁涌出，经塘湾状石池，婉蜒流入亓城峪茶臼河。
** 四十九 大泉
 　　大泉，位于济南南部山区锦锈川乡大泉村。清道光《济南府志》载：“马帝泉，一名大泉，泉流入锦绣川”，拟指此。因水流量大而得名。每小时涌水量达54立方米，汇于面积4000平方米的池塘中，受水位深浅和周围环境的影响，池水呈五彩状，水盛时从溢水口流出，沿九曲河北流入锦锈川。
** 五十 斗母泉
 　　斗母泉，曾名窦姑泉，位于济南市中区南部，青铜山顶部斗母泉村西首。《历城县志》多有记载：“窦姑泉在大佛寺北顶”。泉水自岩壁岩孔流出，汇入石砌方池，清冽甘美，供村民饮用，蓄入封闭式水池，备播种浇地。
** 五十一 芙蓉泉
 　　芙蓉泉位于泉城路芙蓉小吃街中段居民院内。因原池内多植荷花（芙蓉，亦为古时荷花的别称。）而得名。池长10米，宽5米，深3米，块石砌岸，中架石桥，东南西3面连接房屋外壁，北面装雕石栏杆，墙壁和栏板上嵌魏启后、任远等名家书写的泉名、芙蓉泉诗、修复记及居民制定的《爱泉公约》石刻。
** 五十二 腾蛟泉
 　　腾蛟泉位于大明湖南门路南的芙蓉街旁的王府池子街北首东侧，邻近起凤桥街。因西临腾蛟起凤坊得名。泉池呈长方形，长1米，宽0.5米，深1.5米，以青石围砌，精致方正。历城人李亻间（“亻间”为生僻字，故而两字一体，xiàn）于丁卯年（公元1867年）题写的“腾蛟泉”名刻。
** 五十三 濯缨泉
 　　濯缨泉亦称濯缨湖，位于大明湖南门路南的芙蓉街旁的王府池子街中段西侧。取名于《孟子离娄上》“清斯濯缨，浊斯濯足矣”之意命名。清代又因泉由王府划出称王府池。泉池长30米，宽19米，水自池底及西岸岩孔涌出，沿曲溪向北折向东流，穿民居，过石桥，至曲水亭，汇珍珠诸泉水，流经百花洲注入大明湖。
** 五十四 玉环泉
 　　玉环泉俗称玉环井，位于济南泉城路省府前街中段路西，山东省人民政府南侧。因两泉并涌，水纹相扣如玉环而得名。1978年修复，池呈双井形，块石砌成，各装白色大理石雕制的巨石作岸，池周绕石柱铁链围栏。
** 五十五 泮池
     泮池位于济南历下区明湖路府学文庙内，中间为五孔石桥。泮池水自池底涌出，旧时与芙蓉街诸泉汇为一处，从北岸溢水孔溢出，沿暗渠北流入大明湖。泮池乃古代学校的水池。周代天子之学为“辟雍”，诸侯之学称“泮宫”。辟雍有水环绕，泮宫之水只能半之，为半圆形，称为泮池。泮即为半。
** 五十六 双忠泉
 　　双忠泉位于济南市双忠祠街西首北侧（山东省人民政府北门西侧），清康熙年间，修复双忠祠时，掘土出泉，遂以祠命名泉池为两个四方形相叠，面积约8平方米，水深5米，石砌池岸，水质清澈，长年有水。泉池东北角有当代书法家题写的“双忠泉”碑。
** 五十七 洪范池
 　　洪范池位于济南平阴县洪范池镇镇政府北邻的洪范池公园内。《东阿县志》载“池在城南15里群山之中……泉仰吐其上，甃石为池。”以洪水就范之意取名。泉池呈方形，以石砌岸，边长7米，深6米，周置石栏，栏外有平台，泉水自池底及四壁溢出，日涌水量约1000立方米。“不以旱涝而消长，不以冬夏而变温”。由于泉水平稳上浮，将硬币掷于水面上能旋浮多时，经阳光照射，金光闪闪。“洪范浮金”是著名的历史景观。
** 五十八 书院泉
 　　书院泉曾名东流泉，位于济南平阴县洪范池东天池山下书院村，旧《东阿县志》有记载。因明代中丞刘隅曾临泉建书院取名。泉池呈方形，以石砌岸，水自岩隙涌出，汇为边长8米的水池，日涌水量800多立方米，自池南壁石雕龙头口中吐出，沿石渠盘街绕户，穿林润水，流入狼溪河
** 五十九 扈泉
 　　扈泉位于济南平阴县洪范池南约l公里处，云翠山北。因北临扈国都城(遗址)得名。源自山岩壁下部深洞，丰水时，自洞口喷涌而出，触岩击石，浪花飞溅，声传数里，经石坝跌落，形成瀑布，气势壮观。岩壁上镌明代进士孟一脉题“扈泉涌碧”巨字石刻。
** 六十 日月泉
 　　日月泉位于济南平阴县洪范池南，云翠山风景区的“南天观”旧址，因池形如日月而得名。日泉在北，呈圆形，月泉在南，呈弯月形。水自各池岩孔流出，往复流动，长年不涸。周围有天柱峰、笔架山、子陵寨、三清观等自然和历史文化遗迹。
** 六十一 华泉
 　　华泉位于华山风景区华阳宫南侧，因临华不注山而得名。唐段成式《酉阳杂俎》有“华不注泉，方圆百步”的记载。华泉经历了喷涌、淤塞、复涌、再淤塞的过程。2001年，进行清淤挖掘，修砌泉池，池长15米，宽9米，深2米。一池清水，平明如镜，孤山及古庙倒影，与鱼池、荷塘相互映衬，别具风姿。
** 六十二 西麻湾
 　　西麻湾位于济南章丘市明水镇西部。《济南府志》载：“西麻湾在百脉泉右三里许，水自石壑中涌出，东北流……。”今为冲沟式河湾。南起胶济铁路，北至济青公路，长约1500米，宽50米至300米不等。湾底及岸坡，处处泉涌，河渠纵横，游人可手捂泉眼，让泉水从指缝间汩汩上涌。众泉汇聚沿主河道北流。近依泉辟建眼明泉公园。
** 六十三 净明泉
 　　净明泉又名“明水泉”，位于济南章丘市明水镇西麻湾北。因唐王李世民东征至此兵士多患眼疾，以此泉水冲洗，疾除眼明的传说得名。因地下水被截流，停涌多年，村民仍倍加珍惜，古泉池、古庙宇、古桥、古碑皆保存完好。
** 六十四 泥淤泉
 　　泥淤泉（曾名印度泉），位于济南南部山区柳埠镇淤泥泉村。泉因多次被山洪冲击的泥沙淤塞，经挖掘复又成泉，故称淤泥泉。泉池在街道旁，有3个水脉相通的石砌方井池，主泉居东，深10米，底部有洞深不可测，传通于东海，俗称“海眼”，水势旺盛，水自池壁方孔流出，沿石渠流入阎家河。
** 六十五 清泠泉
 　　清泠泉位于济南五峰山风景区的洞真观玉皇殿东侧。因清泉激石，泠泠作响而得名。水自岩壁石雕龙头口中流出，落入边长0.8米的石砌方池。尔后，一脉经溢水口西流，穿石桥入“玉女盆”；一脉至玉皇殿前石桥下水池。清泠泉周围还散布着青龙、白虎等许多历史名泉，形成各具特色的泉水景观
** 六十六 圣水泉
 　　圣水泉位于济南南部山区红叶谷文化旅游区兴教寺内，因泉水有灵气，喝了能长寿的传说而得名。水自岩洞涌出，沿石渠流入方池，清冽甘美，长流不涸，是景区内最古老的天然名泉。
** 六十七 突泉
 　　突泉位于济南南部山区柳埠镇突泉村，此泉水势旺盛，涌出后呈凸起状，故又以其形称突泉。泉池呈井形，长、宽各1米，深7米，以石砌成。水由池上部井壁方孔东流折向南至东西大街南侧沿石渠漫流，形成溪抱渠绕之势，故古时曾称此村为溪抱村。
** 六十八 无影潭
 　　无影潭位于济南天桥区无影山路和无影山中路交叉口东南，无影山公园（济南四五六医院对面居民区内）。因处无影山而得名。此泉由多年掘砂逐渐形成。以石砌岸，面积5000多平方米。水由潭底多处细微的岩孔流出聚成。泉池水面标高31.80米，水深2米至3米，常年不涸。
** 六十九 砚泉
 　　砚池位于姚家村南侧，因地处砚池山而得名。呈塘湾状，是1958年开山采矿石挖成。南北长150米，宽50米左右。水自水深莫测的池底涌出，汇聚池内，常年不涸。池旁立《砚池泉记》碑。
** 七十 迎仙泉
 　　迎仙泉位于济南天桥区顺河高架桥路济南水业集团西北侧约50米处，原来是一处无名泉，2009年9月被正式命名迎仙泉。因泉水发现的地方在英贤街附近，而且旁边有一座桥叫英贤桥，取谐音，名“迎仙泉”。迎仙泉为济南市开放式取水点。泉池四壁用大理石修筑，并且搭建了取水平台，方便市民取水。泉边立有“迎仙泉”石碑。
** 七十一 涌泉
 　　涌泉位于济南南部山区柳埠镇苏家庄四门塔风景区内，四门塔西侧。《历城县志》载：“在神通寺西”，称涌腾泉。泉水自白虎山山腰岩隙涌出，由石雕龙头口中喷入长5米，宽4.5米的石砌方池，再从南岸溢出，依山势三迭而下，形成“悬崖飞瀑”、“细水长流”、“锦上添花”等景观。池旁立明代天启3年(1623年)(重修涌泉碑记)及建于明万历六年的涌泉桥。
** 七十二 玉河泉
 　　玉河泉位于济南市历城区彩石乡玉河泉村。北魏《水经注》称“榆科泉，是巨河水之源”。后泉水汇成一条恰似玉带的河流环绕山村，改称玉河泉，泉自河边岩孔涌出，穿街过户，与东(西)老泉、响呼噜泉等水相汇，沿河北流。
