#+TITLE: polarize training v.s. sweet spot training

** What is the polarize training?
** What is the difference between the 3-zone model and 7-zone model?
** Does polarized is better than sweet spot for people have 10 hour/week?
** Does polarized is better than sweet spot for people have 15 hour/week?
** Does additional zone-2 rides improve the fittness?
** Does the high volume plan ignore the rest?
** What is the value of Trainerroad?
- workout interface
- calendar
- workout creator
- podcast + blog
- forum
- community
*** my opinion
**** It's fun to study, test, evaluate what I've learn
Similar to using Emacs instead of using IDE
** What is the down-side of just following pre-defined plan?
** What is the issue with current Trainerroad user?
*** Too hard to follow a session
** What is the most optimal training plan?
** What is a better option when you are struggling with a workout session?
** How to tink an optimal training plan?
** How to test polarize trainig is better than sweet spot training?
*** I'd like to write a very specific step to perform a test
**** Tests base on time
***** 1,3,5,10,20,60 minutes, what's your best number?
**** Tests with mixed plan
***** The idea is to follow the attacks from the events
** How the efficiency is defined?
** How to listen to your body?
** How do you identify a plateaus?
*** not able to finish the plan
**** how the ratio is defined?
*** not able to push XXX-watts over XXX-mins duaration?
** Why no plan fits all?

We all have different backgrounds before cycling. 

People have different stress in their life, e.g. from jobs, peer pressure, etc.

Motivation is different from people to people. And cycling is sometimes viewed as a mental exercise instead of the body.
** My feeling
*** I am not able to consistently train all year round and I am not sure it is due to the over-prediction FTP. If an updated plan can lower the difficulty inconsistency, but at a cost of a little bit more time, I would definitely want to try the new plan.
**** It's unclear the cost of the time and the difficulty to finish the training session
*** I personally feel not good not able to finish a sessesion but strangely, I cannot finish a session even I sometimes lower the intensity by 10%.
** Interesting post
*** Future
#+BEGIN_QUOTE
ref"https://www.trainerroad.com/forum/t/dylan-johnsons-the-problem-with-trainerroad-training-plans-its-gonna-be-a-busy-day-around-here/53136/725


 The Future is the TrainAsOne running app changes the programme as you complete workouts. Every workout you completes affects your next one.
#+END_QUOTE
*** more advanced plan builder
https://www.trainerroad.com/forum/t/dylan-johnsons-the-problem-with-trainerroad-training-plans-its-gonna-be-a-busy-day-around-here/53136/398
** meta info
register: upto 388
ref: https://www.trainerroad.com/forum/t/dylan-johnsons-the-problem-with-trainerroad-training-plans-its-gonna-be-a-busy-day-around-here/53136
