:PROPERTIES:
:ID:       fdc61b71-1f0b-423e-90c9-3f8a86549e80
:LAST_MODIFIED: [2021-08-11 Wed 16:29]
:END:
#+TITLE: ZK
#+filetags: project casdu
** [[file:./什么是zk.org][什么是ZK]]
** ZK 使用方法
*** 纸制化和电子化的区别
**** 卢曼实现 “transclusion” 的方式
***** 编号
****** 编号本身有助于存档
卢曼在和其 ZK 互动时，很大可能性是将相关卡片摆放在工作桌面。在写作，特别是和 ZK 互动时，纸质卡片的位置肯定是被打乱的。完成一段工作之后，标号的作用是帮助将卡片位置复原。否则无法管理近 90 万条笔记的。

而电子 ZK 的实现中，编号本身的作用被弱化。搜索虽然便捷，但损失掉的这一功能是常常被忽视掉的。
******* 编号作为指针
** Discussion on Internet about ZK
   :PROPERTIES:
   :ID:       dded3d35-b7c2-4c26-b296-ab7df901ec70
   :END:
*** https://www.reddit.com/r/Zettelkasten/
*** https://forum.zettelkasten.de/categories/knowledge-work
*** https://forum.obsidian.md/c/knowledge-management/6
*** https://org-roam.discourse.group/
** [[file:./team_zk.org][TEAM ZK]]
** Difference between ZK and Wiki
#+begin_quote chapter 12
Because the slip-box is not intended to be an encyclopaedia, but a
tool to think with, we don’t need to worry about completeness. We
don’t need to write anything down just to bridge a gap in a note
sequence. We only write if it helps us with our own thinking.

#+end_quote

Only when the gaps become obvious in the next step, it is time to fill
them up.

#+begin_quote https://www.reddit.com/r/Zettelkasten/comments/kndg4s/is_zettelkasten_for_me/
Best description I've seen for a ZK (attributed to someone else here
on reddit, can't recall offhand sorry) is that its a method for
knowledge development rather than a tool for knowledge management.
#+end_quote
*** publish structure note to wiki
    :PROPERTIES:
    :ID:       96fbd9e0-6255-4361-8395-15e87ca35149
    :END:
    - it makes the contributer feel in part of a larger organization
    - it helps the contributer to know the limitation of his point of
      view

** be careful with tag

#+begin_quote
...the references between the notes are much more
important than the references from the index to a single note.
#+end_quote

#+begin_quote
Every consideration on the structure of a topic is just
another consideration on a note
#+end_quote
** Taking action vs thinking
*** I think Zettelkästen is a very special tool.

It servers people's mental activities. Sometime, it is hard to
differentiate between the actions in thoughts and the physical
actions.

For me, Zettelkästen is such tool:

1.  Focus tool. It is the process of forcing myself finding connection
    that makes myself reflect the previous thoughts. This process alone
    is huge motivation for me. I find myself more concentrated and less
    likely to be distracted by the external world if I try to jot down
    something in my mind.

2.  Research tool. This is the primary usage of Zettelkästen. Finding
    connection from my previous thoughts and from other people to
    create new ideas. Although most people are not researchers, the
    thing that we do not to be scientists to do research. The moment of
    finding things that you never know is not too much difference from
    an experienced scientist finding something big scientific
    achievements.

3.  Happiness tool. I feel more easily entering in the [flow state](20201120232129-flow_state.md) in my
    Zettelkästen.

4.  Interaction tool. I am trying to build a team Zettelkästen, which
    has similar idea to Zettelkästen but adding other people's thoughts
    into one Zettelkästen.

Taking action or not upon the same external simulate is different from
people to people. Everybody is different. Karl Friston
<sup id="1f81cff8064db0eb5c458a6df2f00f4b"><a href="#friston2010free" title="Friston, The free-energy principle: a unified brain theory?, {Nature reviews neuroscience}, v(2), 127--138 (2010).">friston2010free</a></sup> proposed that for a system, "the better" is to
choose the reaction that can minimize its free-energy. To achieve
this, one has two options: (1) change sensory input by acting on world
(2) change internal world.

Changing sensory input by acting on world seems more easy, but it will
bring physical pain in many cases. Changing internal world is hard.
Basically, someone has to re-evaluate his/her attitude towards the
external world. To some degree, it's like learning a new language.

If taking action is defined by writing, then I would say yes. It helps
and it helps a lot. The answer to the question becomes blurry when
people take physical activities. For example, chances are low if
someone want to do back flip by interacting with his/her Zettelkästen.
But, I am opening to such claim. In some studies, people can do better
job without really doing things but just mentally imaging something.
** ZK ID
   :PROPERTIES:
   :ID:       006cf19e-060b-4088-a478-773a13eb859f
   :END:
- [[id:752d6262-58f4-424f-843f-edf6e17b6848][forgive the stress on finding]]
*** folgezettel
    :PROPERTIES:
    :ID:       60ab3e2c-b71b-42fa-a4e8-4210e84bf26b
    :END:
    It is a technique to form a hierarchical context. It is useful for
    paper based Zettelkästen, but less useful in digital format.
** Why ZK is useful?
*** [[id:c7be7fb9-5bb2-4309-9145-aae81b109bff][how ZK can affect my habits]]
*** [[id:8588bf22-fbb3-4367-a819-dececaca7df8][why ZK can help you connect ideas]]
*** [[id:006cf19e-060b-4088-a478-773a13eb859f][it reduce the stress]]
Our brain has very limited resources. If any stress is not properly
addressed, then it is hard to let you focus on the present you.It
helps you to write down without worry about anything else.
** guiding ZK direction
   :PROPERTIES:
   :ID:       749e4d0d-321a-44c1-b3c8-2af5e0be02ed
   :END:

I find myself writing a lot of notes when processing the reading notes
from book. Especially [[id:323aca24-9b39-4459-84ca-7188fecc2b2e][the note]] that I track my reading. It is a note
that is arranged in year order. Every year, I like to assign one or
two topic that I want to dig through.

- 2018 and 2019 are the years of Emacs
  Countless time with Emacs that lead me to 2020, the year I meet ZK.
- 2020 is the year of ZK birth
- 2021 is the year about psychology and habits strengthen

** develop new ideas
*** TODO on making connections

 #+transclude: t
 [[file:~/Dropbox/myNote/zk/20200823194039-roaming_in_org_roam_to_find_connection.org][roaming in org-roam to find connection]]

 #+transclude: t
 [[file:~/Dropbox/myNote/zk/20200729232344-how_to_make_connection.org][how to make connection]]

 #+transclude: t
 [[file:~/Dropbox/myNote/zk/20200618163301-interconnection.org][interconnection]]

 continues on writing on how to make new connections across the
 knowledge branch?

**** TODO what is applying the knowledge?
