#+TITLE: 竞技

** Competition can inspire someone to perform at the level s/he can not
to perform if leaving alone. I have some measurements on some of the
sports I've involved. In cycling, the measurements of power is
objective. I often use the power meter to measure how well I perform.
At the same time, I also have another apparatus to measure my
heart rate. It's less objective compared to the power meter but it can
provide some perspectives on my subjective feeling.

What I found is that whenever I am participating in some sort of
competitions, my heart rate is way much higher than the my usual
state. The astonishing point is that my subjective feeling is much
relaxed, which implies that my body can suffer more. I've found this
several time across my life and I also heard from friends sharing the
similar experience.I believe that this is encoded in human's DNA.
Whenever people comes together to chase the non-trivial goal,
individual can have a better performance.

In addition, I found that once I set a reasonable goal, I can be
extremely focus, whatever I do will be enjoyable.

But there is one things need to be extremely clear. It is that the
competition is enjoyable only when it is design to improve ones skill.
