#+TITLE: 竞技

** why it matters?
Competition can inspire someone to perform at the level s/he can not
to perform if leaving alone. I have some measurements on some of the
sports I've involved. In cycling, the measurements of power is
objective. I often use the power meter to measure how well I perform.
At the same time, I also have another apparatus to measure my
heart rate. It's less objective compared to the power meter but it can
provide some perspectives on my subjective feeling.

What I found is that whenever I am participating in some sort of
competitions, my heart rate is way much higher than the my usual
state. The astonishing point is that my subjective feeling is much
relaxed, which implies that my body can suffer more. I've found this
several time across my life and I also heard from friends sharing the
similar experience.I believe that this is encoded in human's DNA.
Whenever people comes together to chase the non-trivial goal,
individual can have a better performance.

In addition, I found that once I set a reasonable goal, I can be
extremely focus, whatever I do will be enjoyable.

But there is one things need to be extremely clear. It is that the
competition is enjoyable only when it is design to improve ones skill.
** [[file:./集体的力量.org][集体的力量]] 也提到了，这种非常奇妙的主观体验。
** 有的时候，我独自一人在路上训练的时候，会碰见和自己实力相当的骑友。通常来说，我是不会跟的。但如果在1分钟以内，他没有跑出我的视线范围，而且如果训练内容是超过 10 分钟的长间歇，我就会选择跟车。为了公平起见，我是不会蹭风的，对手在右我则在左。我会有意识让对手知道我的存在，一是为了安全，二是为了让对手知道有人在和他较量。这种情况下，通常我都会破掉自己的最佳记录。
   :PROPERTIES:
   :ID:       348b83cf-9084-4f9f-88a1-a59db441ea1b
   :END:
