name: commitfiles
on: [push]

jobs:
  job1:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: Set up Emacs
        # You may pin to the exact commit or the version.
        # uses: purcell/setup-emacs@bea3d9e95785b8412caf802b320cd6de386be7a3
        uses: purcell/setup-emacs@v3.0
        with:
          # The version of Emacs to install, e.g. "24.3", or "snapshot" for a recent development version.
          version: 27.1
  
      - name: Modify value # generate pdfs
        run: |
          sudo apt-get update
          sudo apt install texlive-full
      
      - name: Modify value # generate pdfs
        run: |
          cd ../moc
          emacs --batch -l moc/test.el
          
      - name: Commit files # commit the output folder
        run: |
          git config --local user.email "IamBOT@github.com"
          git config --local user.name "BOT"
          git add ../moc/*.pdf
          git commit -m "Pdfs updated"
          
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
